"""Teacher-forced decode-logit parity: fleet_mk vs stock, bucketed by position.

WHY THIS EXISTS
---------------
The standing correctness gate checks `next_token == 35644` at decode iteration 1.
A kernel that is right on token 1 and degrades over 300 tokens passes it clean --
which is exactly the failure we went looking for: fleet_mk's 300-token output showed
single-token near-misses ("Emancipatory Proclamation", "Manifest Doom", "tobaco")
that clustered LATE in the sequence, while stock's did not.

Those are not model confabulation. Confabulation invents confident claims; it does
not misspell "tobacco". They are the signature of logits that are marginally off,
flipping a near-tie. The open question is which of two causes:

  * MXFP4 weights + fp8 activations vs stock's bf16 -- inherent precision loss,
    which would show up as a FLAT disagreement rate across all positions.
  * A real bug in attention state (sliding window, sink correction, KV paging) --
    which would show up as disagreement GROWING with position.

Comparing free-running generations cannot answer this: once the two paths pick
different tokens they have different contexts, and everything after is confounded.
So we teacher-force -- both paths score the SAME token sequence.

METHOD
------
Naively you would feed the full sequence and read prompt_logprobs. That is prefill,
and fleet_mk routes prefill to stock, so it would measure nothing. Instead, for each
sampled position i:

    prompt = prompt_ids + reference[:i]
    generate exactly 2 tokens, capture the logprobs of the SECOND

The second token is a genuine decode step (max_query_len == 1), which is the path
fleet_mk intercepts. Context length grows with i, so bucketing by i is bucketing by
KV-cache depth -- the axis a sliding-window or sink bug would live on.

Plugin registration is process-wide, so each side runs in its own process and dumps
JSON; a third invocation compares.

USAGE
-----
  HIP_VISIBLE_DEVICES=0 VLLM_PLUGINS=      FLEET_MK_MODEL=... \\
      python3 -m fleet_megakernel_vllm.logit_parity --out /tmp/parity_stock.json
  HIP_VISIBLE_DEVICES=0 VLLM_PLUGINS=fleet_mk FLEET_MK_MODEL=... \\
      python3 -m fleet_megakernel_vllm.logit_parity --out /tmp/parity_fleet_mk.json
  python3 -m fleet_megakernel_vllm.logit_parity --compare /tmp/parity_stock.json /tmp/parity_fleet_mk.json

The reference sequence is generated by whichever side runs FIRST and written into
its JSON; the second side is passed --reference to score the identical tokens. The
compare step asserts the two agree, so a stale file cannot silently produce a
meaningless diff.
"""

import argparse
import json
import os

# MUST precede `from vllm import ...` -- vLLM resolves the ROCm attention backend at
# import time. Unconditional so both sides run the SAME attention implementation and
# the only variable is the decode path. See harness.py for the full rationale.
os.environ.setdefault("VLLM_ROCM_USE_AITER", "1")
os.environ.setdefault("VLLM_ROCM_USE_AITER_UNIFIED_ATTENTION", "1")


def _fleet_mk_page_size(model):
    """fleet_mk PAGE_SIZE (== required vLLM block_size) for the selected model."""
    from fleet_megakernel_vllm.spec import load_spec
    name = model.lower()
    arch = ("GptOssForCausalLM" if "gpt-oss" in name or "gpt_oss" in name
            else "Qwen3ForCausalLM")
    return load_spec(arch).page_size


def _build_llm(model, fleet_mk_on):
    from vllm import LLM
    kwargs = dict(model=model, max_num_seqs=1, enforce_eager=True,
                  max_model_len=4096, dtype="bfloat16")
    if fleet_mk_on:
        kwargs["block_size"] = int(
            os.environ.get("FLEET_MK_BLOCK_SIZE", str(_fleet_mk_page_size(model))))
        kwargs["disable_hybrid_kv_cache_manager"] = True
    return LLM(**kwargs)


def _collect(llm, prompt_ids, reference, positions, topk):
    """Score one decode step at each position against the reference prefix."""
    from vllm import SamplingParams
    from vllm.inputs import TokensPrompt

    # max_tokens=2: token 1 comes from prefill (stock on both sides), token 2 is a
    # real decode step. min_tokens + ignore_eos so an EOS cannot short a sample and
    # silently drop a position from the curve.
    sp = SamplingParams(temperature=0.0, max_tokens=2, min_tokens=2,
                        ignore_eos=True, logprobs=topk, seed=0)

    prompts = [TokensPrompt(prompt_token_ids=list(prompt_ids) + list(reference[:i]))
               for i in positions]
    outs = llm.generate(prompts, sp, use_tqdm=True)

    rows = []
    for i, out in zip(positions, outs):
        o = out.outputs[0]
        lp = o.logprobs[1]        # index 1 == the decode step
        ranked = sorted(lp.items(), key=lambda kv: kv[1].rank)
        rows.append({
            "position": i,
            "ctx_len": len(prompt_ids) + i + 1,   # +1 for the prefill-emitted token
            "top1": int(ranked[0][0]),
            "topk": [[int(t), float(v.logprob)] for t, v in ranked],
        })
    return rows


def run_one(args):
    model = os.environ.get("FLEET_MK_MODEL", "Qwen/Qwen3-8B")
    fleet_mk_on = bool(os.environ.get("VLLM_PLUGINS"))
    label = "fleet_mk" if fleet_mk_on else "stock"

    llm = _build_llm(model, fleet_mk_on)
    tok = llm.get_tokenizer()
    text = tok.apply_chat_template([{"role": "user", "content": args.prompt}],
                                   tokenize=False, add_generation_prompt=True)
    prompt_ids = tok(text).input_ids

    if args.reference:
        with open(args.reference) as f:
            ref_blob = json.load(f)
        reference = ref_blob["reference"]
        assert ref_blob["prompt_ids"] == prompt_ids, (
            "prompt token ids differ between the two sides -- the reference file was "
            "produced with a different prompt or tokenizer; the comparison would be "
            "meaningless.")
        print(f"[{label}] scoring {len(reference)} reference tokens from {args.reference}")
    else:
        from vllm import SamplingParams
        from vllm.inputs import TokensPrompt
        print(f"[{label}] generating a fresh {args.n_tokens}-token reference")
        out = llm.generate(
            [TokensPrompt(prompt_token_ids=prompt_ids)],
            SamplingParams(temperature=0.0, max_tokens=args.n_tokens,
                           min_tokens=args.n_tokens, ignore_eos=True, seed=0),
            use_tqdm=True)
        reference = list(out[0].outputs[0].token_ids)

    positions = list(range(0, len(reference), args.stride))
    print(f"[{label}] scoring {len(positions)} positions, stride {args.stride}")
    rows = _collect(llm, prompt_ids, reference, positions, args.topk)

    blob = {
        "label": label, "model": model, "prompt": args.prompt,
        "prompt_ids": prompt_ids, "reference": reference,
        "stride": args.stride, "topk": args.topk, "rows": rows,
    }
    with open(args.out, "w") as f:
        json.dump(blob, f)
    print(f"[{label}] wrote {args.out}  ({len(rows)} positions)")


def _buckets(n_ctx_max):
    """Position buckets. A sliding-window/sink bug should show a step; precision
    loss should be flat. 128 is GPT-OSS's sliding window -- the boundary matters."""
    edges = [0, 64, 128, 256, 512, 1024, 10 ** 9]
    return [(lo, hi) for lo, hi in zip(edges, edges[1:]) if lo < n_ctx_max]


def compare(path_a, path_b):
    with open(path_a) as f:
        a = json.load(f)
    with open(path_b) as f:
        b = json.load(f)

    assert a["reference"] == b["reference"], (
        "the two runs scored DIFFERENT reference sequences -- rerun the second side "
        "with --reference pointing at the first side's JSON.")
    assert a["prompt_ids"] == b["prompt_ids"], "prompt token ids differ"

    ra = {r["position"]: r for r in a["rows"]}
    rb = {r["position"]: r for r in b["rows"]}
    shared = sorted(set(ra) & set(rb))
    assert shared, "no overlapping positions between the two runs"

    print(f"\n===== teacher-forced decode-logit parity =====")
    print(f"A = {a['label']:<6} ({path_a})")
    print(f"B = {b['label']:<6} ({path_b})")
    print(f"model     : {a['model']}")
    print(f"positions : {len(shared)}  (stride {a['stride']}, top-{a['topk']} logprobs)")
    print(f"reference : {len(a['reference'])} tokens, generated by "
          f"{'A' if not a.get('from_reference') else 'B'}\n")

    ctx_max = max(ra[p]["ctx_len"] for p in shared)
    print(f"{'ctx window':>14} | {'n':>4} | {'top-1 agree':>11} | {'mean rank of A-top1 in B':>24}")
    print("-" * 64)

    overall_agree = 0
    for lo, hi in _buckets(ctx_max):
        sel = [p for p in shared if lo <= ra[p]["ctx_len"] < hi]
        if not sel:
            continue
        agree = sum(1 for p in sel if ra[p]["top1"] == rb[p]["top1"])
        overall_agree += agree
        ranks = []
        for p in sel:
            want = ra[p]["top1"]
            hit = next((k for k, (t, _) in enumerate(rb[p]["topk"]) if t == want), None)
            # Miss => not in B's top-k at all. Charge topk+1 rather than dropping it,
            # else the worst disagreements silently improve the average.
            ranks.append(hit + 1 if hit is not None else b["topk"] + 1)
        span = f"{lo}-{hi if hi < 10**9 else ''}"
        print(f"{span:>14} | {len(sel):>4} | {100.0*agree/len(sel):>10.1f}% | "
              f"{sum(ranks)/len(ranks):>24.2f}")

    print("-" * 64)
    print(f"{'ALL':>14} | {len(shared):>4} | {100.0*overall_agree/len(shared):>10.1f}% |\n")

    print("Reading this:")
    print("  * agreement FLAT across buckets  -> MXFP4/fp8 precision loss (inherent)")
    print("  * agreement FALLS with ctx depth -> a real bug; the bucket where it")
    print("    turns localizes it (128 is GPT-OSS's sliding window boundary)")

    first = [p for p in shared if ra[p]["top1"] != rb[p]["top1"]][:12]
    if first:
        print(f"\nFirst {len(first)} disagreements (position, ctx, A-top1, B-top1):")
        for p in first:
            print(f"  pos {p:>4}  ctx {ra[p]['ctx_len']:>5}  "
                  f"A={ra[p]['top1']:>7}  B={rb[p]['top1']:>7}")


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", default="/tmp/parity.json")
    ap.add_argument("--reference", help="JSON from the other side; score ITS tokens")
    ap.add_argument("--compare", nargs=2, metavar=("A", "B"))
    ap.add_argument("--prompt", default=os.environ.get(
        "FLEET_MK_PROMPT", "Tell me the history of America."))
    ap.add_argument("--n-tokens", type=int, default=400)
    ap.add_argument("--stride", type=int, default=8)
    ap.add_argument("--topk", type=int, default=20)
    args = ap.parse_args()

    if args.compare:
        compare(*args.compare)
    else:
        run_one(args)


if __name__ == "__main__":
    main()
