# GPU Backend Selection: Use either USE_CUDA or USE_ROCM, not both
set(USE_CUDA OFF)
set(USE_ROCM ON)
set(CMAKE_BUILD_TYPE DEBUG)
set(CMAKE_VERBOSE_MAKEFILE ON)
set(USE_CUDNN OFF)
set(BUILD_CPP_EXAMPLES OFF)
set(USE_NKI OFF)
set(USE_FORMAL_VERIFIER OFF)
