#!/bin/bash
# Auto-generated by fleet_mk_generate.py
# Fleet MK build script for gpt-oss-120b on gfx950
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
FLEET_MK_DIR="$SCRIPT_DIR"
GEN_DIR="${1:-$SCRIPT_DIR/generated}"

ROCM_PATH="${ROCM_PATH:-/opt/rocm}"
HIPCC="${ROCM_PATH}/bin/hipcc"

# Fleet MK compiles against fleet's header tree ONLY -- ROCm/fleet-chiplet-megakernel,
# branch amd_mi355_gpt_oss120b. Nothing here may point at mirage
# (github.com/sangeeta0201/mirage): that is a personal fork, and fleet_mk carrying a
# build-time dependency on it is exactly what this flip removes. Fleet is public
# and is the single source of truth.
#
# Fleet's tree is used OUT OF THE BOX -- it is on the include path, never copied
# and never edited. A vendored copy would be a fork that silently rots; -I at
# fleet's own checkout means future fleet work lands automatically.
#
# The old -I"$HIP_COMPAT" line is deleted rather than repointed: that directory
# does not exist in either tree, so it was always a dead path.
FLEET_DIR="${FLEET_DIR:-/home/claudeuser/fleet-chiplet-megakernel}"
CK_DIR="${CK_DIR:-/home/claudeuser/composable_kernel_mirage}"

MPK_INCLUDE="$FLEET_DIR/include/mirage/persistent_kernel"

# Three defines fleet's Python driver (persistent_kernel.py) normally supplies and
# fleet_mk must now supply itself. Verified against fleet @ f3c40ed: NEITHER of the
# first two has an in-header default -- the only #define of
# MPK_MAX_NUM_BATCHED_REQUESTS in the tree is commented out
# (persistent_kernel.cuh:556), and MPK_PREFETCH_NEXT_QKV is a bare #ifdef at
# three sites. Omitting either is a SILENT miscompile, not a build error:
#
#   FLEET_MK_FLEET_HEADERS         selects fleet's calling convention in the
#                               generated kernel -- the trailing runtime arg is
#                               task_layer_idx in fleet, sliding_window_override
#                               in mirage, and neither header diagnoses receiving
#                               the other's. Also selects the two-instantiation
#                               form, since fleet takes the window as a template
#                               parameter only.
#   MPK_MAX_NUM_BATCHED_REQUESTS=1   fleet_mk is bs=1 decode.
#   MPK_PREFETCH_NEXT_QKV       default ON in fleet; the reason for the migration.
#
# MPK_NO_LAYER_BARRIER is deliberately NOT passed: fleet's cross-XCD layer
# barrier is the one that survives, and fleet_mk's own has been removed.

# W13 direct-to-LDS weight prefetch is ON by default. Set FLEET_MK_NO_W13_PREFETCH=1
# to build the HBM-direct path instead -- the only supported way to get an A/B
# pair that differs ONLY in the prefetch, which matters because the MoE fault
# under investigation reproduces about one run in three. Comparing a prefetch-ON
# build against a prefetch-OFF build that also differs in K stride or scale
# split cannot attribute anything.
if [ -n "$FLEET_MK_NO_W13_PREFETCH" ]; then
  W13_PREFETCH_FLAG=""
else
  W13_PREFETCH_FLAG="-DMPK_W13_LDS_PREFETCH"
fi

echo "=== Fleet MK gpt-oss-120b Build ==="
echo "  Source: $GEN_DIR/gpt_oss_120b_launch.hip"
echo "  Target: gfx950"
echo "  Output: $GEN_DIR/gpt_oss_120b.so"

$HIPCC -x hip "$GEN_DIR/gpt_oss_120b_launch.hip" \
    -O3 \
    -std=c++17 \
    -fPIC \
    -fgpu-rdc \
    --offload-arch=gfx950 \
    -I"$FLEET_MK_DIR/kernels" \
    -I"$FLEET_MK_DIR/generated" \
    -I"$MPK_INCLUDE" \
    -I"$FLEET_DIR/include" \
    -I"$ROCM_PATH/include" \
    -I"$CK_DIR/include" \
    -D__HIP_PLATFORM_AMD__=1 \
    -DMIRAGE_AMD_MI300 \
    -DMIRAGE_BACKEND_USE_ROCM \
    -DMPK_USE_CK_FMHA \
    -DFLEET_MK_TARGET_GFX950 \
    -DMPK_TARGET_CC=95 \
    -DMPK_ROUTER_FUSED_DP \
    -DMPK_ROUTER_DUAL_REDUCE \
    -DMPK_W13_LINEAR_LOAD \
    -DMPK_W13_T1_LINEAR_LOAD \
    -DMPK_W13_PREQUANT \
    -DMPK_W13_T0_COUNTED_HANDOFF \
    -DMPK_W13_T0_MFMA_UNROLLED \
    -DMPK_W2_T0_MFMA_UNROLLED \
    -DMPK_W13_T1_EARLY_SCALE_LOAD \
    -DMPK_W13_KMAJOR_RECYCLE \
    -DMPK_W13_BIAS_PREFETCH \
    -DMPK_W2_CONSUMER_GATE \
    -DMPK_W2_ONLY_ARRIVE \
    -DMPK_WIDE_FP8_QUANT \
    -DMPK_XCD_LOCAL_BARRIER \
    -DMPK_OPROJ_TREE_BARRIER \
    -DMPK_OPROJ_NO_WB \
    -DMPK_OPROJ_KMAJOR \
    -DMPK_ONE_NORM_WRITER \
    -DMPK_LEAN_ARRIVE \
    -DMPK_QKV_LDS_NORM \
    -DMPK_QKV_PREFETCH_SCALES \
    -DMPK_RMSNORM_DPP_REDUCE \
    -DMPK_TOPK_LOCAL_MAX3 \
    -DMPK_ML_TABLE_PREFETCH \
    -DMPK_MERGE_TWO_PASS \
    -DMPK_MERGE_KV_OUTER \
    -DMPK_ATTN_SLICE_RELEASE \
    -DMPK_SYS_POLL_LOAD=2 \
    -DFLEET_MK_FLEET_HEADERS \
    -DMPK_MAX_NUM_BATCHED_REQUESTS=1 \
    -DMPK_PREFETCH_NEXT_QKV \
    $W13_PREFETCH_FLAG \
    -DCK_TILE_FMHA_FWD_FAST_EXP2=1 \
    ${FLEET_MK_SUBPHASE_TIMING:+-DFLEET_MK_SUBPHASE_TIMING} \
    ${FLEET_MK_TIMER_PRINT:+-DFLEET_MK_TIMER_PRINT} \
    ${FLEET_MK_EXTRA_DEFINES:+$FLEET_MK_EXTRA_DEFINES} \
    -Rpass-analysis=kernel-resource-usage \
    -shared \
    -o "$GEN_DIR/gpt_oss_120b.so"

echo "=== Build complete: $GEN_DIR/gpt_oss_120b.so ==="
