#!/bin/bash
# Auto-generated by titan_generate.py
# Titan build script for gpt-oss-120b on gfx950
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
TITAN_DIR="$SCRIPT_DIR"
GEN_DIR="${1:-$SCRIPT_DIR/generated}"

ROCM_PATH="${ROCM_PATH:-/opt/rocm}"
HIPCC="${ROCM_PATH}/bin/hipcc"

# Titan compiles against fleet's header tree ONLY -- ROCm/fleet-chiplet-megakernel,
# branch amd_mi355_gpt_oss120b. Nothing here may point at mirage
# (github.com/sangeeta0201/mirage): that is a personal fork, and titan carrying a
# build-time dependency on it is exactly what this flip removes. Fleet is public
# and is the single source of truth.
#
# Fleet's tree is used OUT OF THE BOX -- it is on the include path, never copied
# and never edited. A vendored copy would be a fork that silently rots; -I at
# fleet's own checkout means future fleet work lands automatically.
#
# The old -I"$HIP_COMPAT" line is deleted rather than repointed: that directory
# does not exist in either tree, so it was always a dead path.
FLEET_DIR="${FLEET_DIR:-/home/claudeuser/fleet-chiplet-megakernel}"
CK_DIR="${CK_DIR:-/home/claudeuser/composable_kernel_mirage}"

MPK_INCLUDE="$FLEET_DIR/include/mirage/persistent_kernel"

# Three defines fleet's Python driver (persistent_kernel.py) normally supplies and
# titan must now supply itself. Verified against fleet @ f3c40ed: NEITHER of the
# first two has an in-header default -- the only #define of
# MPK_MAX_NUM_BATCHED_REQUESTS in the tree is commented out
# (persistent_kernel.cuh:556), and MPK_PREFETCH_NEXT_QKV is a bare #ifdef at
# three sites. Omitting either is a SILENT miscompile, not a build error:
#
#   TITAN_FLEET_HEADERS         selects fleet's calling convention in the
#                               generated kernel -- the trailing runtime arg is
#                               task_layer_idx in fleet, sliding_window_override
#                               in mirage, and neither header diagnoses receiving
#                               the other's. Also selects the two-instantiation
#                               form, since fleet takes the window as a template
#                               parameter only.
#   MPK_MAX_NUM_BATCHED_REQUESTS=1   titan is bs=1 decode.
#   MPK_PREFETCH_NEXT_QKV       default ON in fleet; the reason for the migration.
#
# MPK_NO_LAYER_BARRIER is deliberately NOT passed: fleet's cross-XCD layer
# barrier is the one that survives, and titan's own has been removed.

# W13 direct-to-LDS weight prefetch is ON by default. Set TITAN_NO_W13_PREFETCH=1
# to build the HBM-direct path instead -- the only supported way to get an A/B
# pair that differs ONLY in the prefetch, which matters because the MoE fault
# under investigation reproduces about one run in three. Comparing a prefetch-ON
# build against a prefetch-OFF build that also differs in K stride or scale
# split cannot attribute anything.
if [ -n "$TITAN_NO_W13_PREFETCH" ]; then
  W13_PREFETCH_FLAG=""
else
  W13_PREFETCH_FLAG="-DMPK_W13_LDS_PREFETCH"
fi

echo "=== Titan gpt-oss-120b Build ==="
echo "  Source: $GEN_DIR/gpt_oss_120b_launch.hip"
echo "  Target: gfx950"
echo "  Output: $GEN_DIR/gpt_oss_120b.so"

$HIPCC -x hip "$GEN_DIR/gpt_oss_120b_launch.hip" \
    -O3 \
    -std=c++17 \
    -fPIC \
    -fgpu-rdc \
    --offload-arch=gfx950 \
    -I"$TITAN_DIR/kernels" \
    -I"$TITAN_DIR/generated" \
    -I"$MPK_INCLUDE" \
    -I"$FLEET_DIR/include" \
    -I"$ROCM_PATH/include" \
    -I"$CK_DIR/include" \
    -D__HIP_PLATFORM_AMD__=1 \
    -DMIRAGE_AMD_MI300 \
    -DMIRAGE_BACKEND_USE_ROCM \
    -DMPK_USE_CK_FMHA \
    -DTITAN_TARGET_GFX950 \
    -DMPK_TARGET_CC=95 \
    -DTITAN_FLEET_HEADERS \
    -DMPK_MAX_NUM_BATCHED_REQUESTS=1 \
    -DMPK_PREFETCH_NEXT_QKV \
    $W13_PREFETCH_FLAG \
    -DCK_TILE_FMHA_FWD_FAST_EXP2=1 \
    ${TITAN_SUBPHASE_TIMING:+-DTITAN_SUBPHASE_TIMING} \
    ${TITAN_EXTRA_DEFINES:+$TITAN_EXTRA_DEFINES} \
    -Rpass-analysis=kernel-resource-usage \
    -shared \
    -o "$GEN_DIR/gpt_oss_120b.so"

echo "=== Build complete: $GEN_DIR/gpt_oss_120b.so ==="
