#!/usr/bin/env python3
"""Auto-generated by fleet_mk_generate.py
Fleet MK demo for gpt-oss-120b inference using two-level fusion.

Loads gpt-oss-120b weights from HuggingFace, quantizes to MXFP4, builds the
pointer table for the gpt-oss-120b persistent kernel, runs prefill via PyTorch,
then decode via the fleet_mk kernel.

Usage:
    HIP_VISIBLE_DEVICES=0 python3 demo_gpt_oss_120b.py \
        --model Gpt/GPT-OSS-120B \
        --prompt "Tell me the history of america" --max-seq-length 512
"""

import argparse
import ctypes
import gc
import json
import math
import os
import sys
import time

import torch
import yaml
from safetensors import safe_open

# Weight packing primitives. These live in fleet_mk now (fleet_megakernel_vllm/mxfp4_pack.py,
# a verified copy of mirage's demo.py originals) rather than being imported out
# of the mirage checkout at runtime -- the vLLM plugin already depends on the
# local copy, and the two packers must agree byte-for-byte or the two entry
# points build different slabs for the same kernel.
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from fleet_megakernel_vllm.mxfp4_pack import (  # noqa: E402
    pad_weight_1d, pad_weight_2d, quantize_bf16_to_mxfp4, pack_mxfp4_workgroup)

from transformers import AutoTokenizer, AutoModelForCausalLM

# -- gpt-oss-120b constants --
HIDDEN_SIZE = 2944
ACTUAL_HIDDEN_DIM = 2880  # for RMSNorm mean
INTERMEDIATE_SIZE = 2944
VOCAB_SIZE = 201088
PADDED_VOCAB_SIZE = 201216  # next multiple for LM head split
NUM_LAYERS = 36
NUM_Q_HEADS = 64
NUM_KV_HEADS = 8
HEAD_DIM = 64
Q_PER_KV = NUM_Q_HEADS // NUM_KV_HEADS  # 8
QKV_OUTPUT_SIZE = NUM_Q_HEADS * HEAD_DIM + 2 * NUM_KV_HEADS * HEAD_DIM  # 5120

# All GEMMs use OPW=64
OUTPUT_PER_WG = 64
NUM_XCDS = 8
WORKERS_PER_XCD = 30
TOTAL_WORKERS = NUM_XCDS * WORKERS_PER_XCD
NUM_KV_CHUNKS = 8

# Per-XCD workgroup counts
QKV_N_WGS_PER_XCD = (QKV_OUTPUT_SIZE // OUTPUT_PER_WG) // NUM_XCDS  # 10
OPROJ_REDUCTION = NUM_Q_HEADS * HEAD_DIM  # 4096
OPROJ_OPW = 16
OPROJ_N_WGS = HIDDEN_SIZE // OPROJ_OPW  # 184 (global distribution)
OPROJ_N_WGS_PER_XCD = OPROJ_N_WGS // NUM_XCDS  # 23
# MoE expert dimensions
NUM_EXPERTS = 128
NUM_TOPK = 4
MOE_INTERMEDIATE_SIZE = 2944

# ── MoE weight row stride (expert weights only) ──────────────────────────────
# How far apart consecutive expert weight ROWS are stored, in K values. This is
# NOT the reduction length: the MFMA always sums HIDDEN_SIZE (2944) columns, 23
# iterations of 16x16x128, whatever this is set to. The two are separate because
# the row pitch belongs to whoever wrote the buffer, and the reduction belongs to
# the MFMA -- see MPK_MOE_K_STRIDE in gang_moe_fused_mxfp4_mi300.cuh.
#
# It is only ever non-default when fleet_mk reads expert weights out of an
# allocation someone else padded. vLLM rounds GPT-OSS's K to 3072, so its rows
# sit 1536 B apart; to alias that memory rather than copy it, fleet_mk has to walk
# rows at ITS pitch while still reducing 2944. Setting this here packs fleet_mk's
# own slab the same way, which exercises the kernel's stride path without vLLM
# in the picture.
#
# MUST equal the -DMPK_MOE_K_STRIDE the .so was built with (0/unset means "same
# as the reduction"). A mismatch does not fail the build -- it reads every
# expert row at the wrong offset and produces fluent-looking garbage.
MOE_K_STRIDE = int(os.environ.get("FLEET_MK_MOE_K_STRIDE", "0")) or HIDDEN_SIZE
assert MOE_K_STRIDE >= HIDDEN_SIZE and MOE_K_STRIDE % 32 == 0, (
    f"MOE_K_STRIDE={MOE_K_STRIDE} must be a multiple of 32 and at least the "
    f"{HIDDEN_SIZE}-wide reduction")
MOE_K_STRIDE_BLOCKS = MOE_K_STRIDE // 32

# ── MoE scale placement ──────────────────────────────────────────────────────
# 0: scales interleaved per workgroup -- [data][scales][data][scales]... This is
#    what fleet_mk has always packed, and the kernel finds a workgroup's scales by
#    walking WG_DATA bytes past its own data.
# 1: split -- [all data][all scales], two contiguous sections addressed with
#    independent bases and pitches.
#
# The split mode is the shape vLLM's memory already has: w13_weight and
# w13_weight_scale are two separate tensors, and no offset from one reaches the
# other. Keeping them adjacent in ONE allocation here exercises the whole
# split-addressing path in the kernel without yet having to widen the pointer
# table -- the kernel derives the scale base from the data base. The later step
# that aliases vLLM's memory only changes where that base comes from.
#
# MUST equal the -DMPK_MOE_SPLIT_SCALES the .so was built with. Like the stride
# knob, a mismatch is silent: it reads real scale bytes for the wrong rows.
MOE_SPLIT_SCALES = os.environ.get("FLEET_MK_MOE_SPLIT_SCALES", "0") == "1"

# ── MoE data/scale allocation split ──────────────────────────────────────────
# Split mode puts the two sections in ONE allocation, adjacent, so the scale base
# is data_base + NUM_EXPERTS*EXPERT_BYTES. That is a convenience, not something
# the kernel requires: since the pointer table carries the two bases separately,
# the sections may live in unrelated allocations.
#
# This knob makes them so. It buys nothing on its own -- same bytes, same
# addresses modulo the allocator -- and that is exactly the point: it is the last
# structural difference between fleet_mk's slab and the arrangement where the DATA
# pointer belongs to vLLM and only the SCALE pointer is fleet_mk's. Exercising it on
# fleet_mk's own bytes first isolates "two allocations" from "someone else's bytes",
# so that if the aliased run misbehaves, this is already ruled out.
#
# Costs no .so flag: the kernel takes both bases as arguments and never assumes a
# relationship between them.
MOE_SPLIT_BUFFERS = os.environ.get("FLEET_MK_MOE_SPLIT_BUFFERS", "0") == "1"

# ── Fleet QKV weight prefetch hand-off (input_ptrs[24]/[25]) ─────────────────
# ON (the default) puts the QKV weight pointers fleet actually reads in those
# slots. OFF restores fleet_mk's MoE scale bases, which is what shipped before and
# what every -DMPK_PREFETCH_NEXT_QKV build ran with. See the long note at the
# [24]/[25] entries in the pointer table for the mechanism.
#
# Kept as a knob rather than a straight edit because the two arms differ in
# exactly two host-side integers -- same .so, same defines, same everything --
# which makes it the cleanest A/B available and the only way to get a control
# run without a rebuild. Both arms are correct; they differ in cost.
FLEET_MK_QKV_PF = os.environ.get("FLEET_MK_QKV_PF", "1") == "1"

# ── MoE slab tail pad (DIAGNOSTIC) ───────────────────────────────────────────
# Bytes of dead space appended to the END of each packed expert slab. Purely a
# probe for reads that run off the end: it moves no base and no section offset
# (data still starts at byte 0, scales still at NUM_EXPERTS*EXPERT_BYTES), it
# only makes the addresses just past the last scale byte legal instead of
# faulting. So a run that faults at pad=0 and survives at pad=1MiB is reading
# past the buffer -- the pad does not FIX that, it hides it, which is exactly
# what makes it a usable bisection signal.
# Set to -1 for a PURE RELOCATION: copy each slab to a fresh allocation with
# zero extra bytes. This is the control for the pad experiment. A pad does two
# things at once -- it adds legal bytes past the end AND it moves the buffer to
# a different address -- and only the first is evidence of an overrun. If -1
# also survives, the pad proved nothing about reads running off the end and the
# fault is address- or allocator-dependent instead.
MOE_TAIL_PAD = int(os.environ.get("FLEET_MK_MOE_TAIL_PAD", "0"))

# Which expert slabs the pad applies to: "both" (default), "w13", or "w2".
# Padding one at a time says WHICH tensor is overrun, which the combined run
# cannot: both slabs are rebuilt together otherwise.
MOE_TAIL_PAD_SLOT = os.environ.get("FLEET_MK_MOE_TAIL_PAD_SLOT", "both")
assert MOE_TAIL_PAD_SLOT in ("both", "w13", "w2")

assert not MOE_SPLIT_BUFFERS or MOE_SPLIT_SCALES, (
    "FLEET_MK_MOE_SPLIT_BUFFERS requires FLEET_MK_MOE_SPLIT_SCALES=1 -- there are no "
    "separable sections to allocate apart while they are interleaved per "
    "workgroup")

# ── MoE expert row pitch (N axis) ────────────────────────────────────────────
# How many ROWS one expert occupies in the data section, against how many rows
# the kernel computes. Same stride-vs-extent split as MOE_K_STRIDE, one axis
# over: the pitch belongs to whoever wrote the buffer, the row count belongs to
# the tiles.
#
# vLLM pads BOTH axes to a multiple of 256, so its experts sit 6144/3072 rows
# apart while fleet_mk computes 5888/2944. Unlike the K pad, these extra rows are
# never addressed by any tile -- no MFMA sums them -- so their content is
# irrelevant rather than required-zero.
#
# Set in units of the INTERMEDIATE/HIDDEN row count (3072 for vLLM), not of
# W13's doubled axis; the packer's W13 call doubles it, matching the kernel's
# W13_N_STRIDE = 2 * MPK_MOE_N_STRIDE.
#
# MUST equal the -DMPK_MOE_N_STRIDE the .so was built with. Requires split mode
# on both sides: a foreign expert pitch implies a foreign buffer, which cannot
# also carry fleet_mk's per-workgroup interleaved scales.
MOE_N_STRIDE = int(os.environ.get("FLEET_MK_MOE_N_STRIDE", "0"))
assert not MOE_N_STRIDE or MOE_SPLIT_SCALES, (
    "FLEET_MK_MOE_N_STRIDE requires FLEET_MK_MOE_SPLIT_SCALES=1")
assert not MOE_N_STRIDE or MOE_N_STRIDE >= HIDDEN_SIZE, (
    f"MOE_N_STRIDE={MOE_N_STRIDE} is shorter than the {HIDDEN_SIZE} rows W2 "
    f"computes -- experts would overlap")
# One knob covers both axes only because GPT-OSS pads hidden and intermediate
# alike (fleet_mk 2944/2944, vLLM 3072/3072). The kernel static_asserts this too.
assert not MOE_N_STRIDE or HIDDEN_SIZE == MOE_INTERMEDIATE_SIZE, (
    "one N-stride knob assumes hidden and intermediate pad alike")

# Must match W13_OPW in generated/gpt_oss_120b_kernel.cuh (weight packing layout).
# MEASURED: W13_OPW=64 (with MOE_TOTAL_TILES_PER_XCD=83) removes the padding
# waste and drops W13_TILES_PER_WAVE 2->1, but is 280us/tok WORSE (2.818 vs
# 2.537ms). Note this is the OPPOSITE sign to W2_OPW below: W13 wants fat tiles
# (it reuses one LDS weight load across two MFMA rounds), W2 wants thin ones.
# Do not "symmetrize" these two constants.
W13_OPW = 128
W13_OUTPUT_SIZE = 2 * MOE_INTERMEDIATE_SIZE
W13_N_WGS = W13_OUTPUT_SIZE // W13_OPW  # 46
# Rows one expert occupies in the DATA section. W13 is gate+up interleaved, so a
# foreign N stride counts intermediate rows and this axis holds two of them --
# the kernel's W13_N_STRIDE uses the identical expression.
W13_N_STRIDE = 2 * MOE_N_STRIDE if MOE_N_STRIDE else W13_OUTPUT_SIZE
assert W13_N_STRIDE % W13_OPW == 0, "W13 expert pitch is not a whole number of workgroups"
W13_DATA_WGS = W13_N_STRIDE // W13_OPW
# Data bytes stride, scale bytes reduce -- the kernel derives row_data_base from
# K_STRIDE and row_scale_base from K_REDUCE independently. In split mode the
# workgroup pitch covers DATA ONLY, exactly as W13_WG_BYTES does in the kernel;
# these must stay the same expression on both sides.
W13_WG_DATA = W13_OPW * (MOE_K_STRIDE // 2)
W13_WG_SCALE = W13_OPW * (HIDDEN_SIZE // 32)
W13_WG_BYTES = W13_WG_DATA if MOE_SPLIT_SCALES else (W13_WG_DATA + W13_WG_SCALE)
# Pitch from one expert's data to the next: keyed on the STORED row count, not
# the computed one. Identical to W13_N_WGS whenever MOE_N_STRIDE is unset.
W13_EXPERT_BYTES = W13_DATA_WGS * W13_WG_BYTES
# Must match W2_OPW in generated/gpt_oss_120b_kernel.cuh — this controls the
# weight packing layout, so a mismatch silently produces garbage output.
# MEASURED: W2_OPW=128 (with MOE_TOTAL_TILES_PER_XCD=42) halves the W2 tile
# count and enables W2_TILES_PER_WAVE=2 cross-tile pipelining, but is 142us/tok
# WORSE (2517 vs 2375us device time). Fewer, fatter W2 tiles cut the parallelism
# that was hiding W2's HBM latency. Do not "fix" this back to 128.
W2_OPW = 64
W2_N_WGS = HIDDEN_SIZE // W2_OPW  # 46
# W2's output axis is hidden, so the foreign N stride applies once here against
# W13's twice.
W2_N_STRIDE = MOE_N_STRIDE if MOE_N_STRIDE else HIDDEN_SIZE
assert W2_N_STRIDE % W2_OPW == 0, "W2 expert pitch is not a whole number of workgroups"
W2_DATA_WGS = W2_N_STRIDE // W2_OPW
W2_WG_DATA = W2_OPW * (MOE_K_STRIDE // 2)
W2_WG_SCALE = W2_OPW * (MOE_INTERMEDIATE_SIZE // 32)
W2_WG_BYTES = W2_WG_DATA if MOE_SPLIT_SCALES else (W2_WG_DATA + W2_WG_SCALE)
W2_EXPERT_BYTES = W2_DATA_WGS * W2_WG_BYTES
ROUTER_OUTPUT_SIZE = 128
ROUTER_N_WGS = ROUTER_OUTPUT_SIZE // OUTPUT_PER_WG  # 2
LM_N_WGS_PER_XCD = (PADDED_VOCAB_SIZE // OUTPUT_PER_WG) // NUM_XCDS  # 393

# MXFP4 workgroup byte sizes
QKV_WG_BYTES = OUTPUT_PER_WG * (HIDDEN_SIZE // 2 + HIDDEN_SIZE // 32)
OPROJ_WG_BYTES = OPROJ_OPW * (OPROJ_REDUCTION // 2 + OPROJ_REDUCTION // 32)  # 34816 for OPW=16
ROUTER_WG_BYTES = OUTPUT_PER_WG * (HIDDEN_SIZE // 2 + HIDDEN_SIZE // 32)
# W13/W2 WG_BYTES defined above
LM_WG_BYTES = OUTPUT_PER_WG * (HIDDEN_SIZE // 2 + HIDDEN_SIZE // 32)

# Pointer table layout: pre-computed mirage format
# 26 mirage_in + 11 mirage_out + 1 layer_output = 38 per layer per XCD
MIRAGE_IN = 26
MIRAGE_OUT = 11
PTRS_PER_LAYER = MIRAGE_IN + MIRAGE_OUT + 1  # 38

# Counter slot offsets (must match kernel .cuh)
#
# This is the pointer handed to the layer body as input_ptrs[7] (the per-XCD
# QKV epoch arrival line), so it must not alias any slot the layer body itself
# uses. The layer body owns lines 0..72: 0..9 oproj, 10..18 routing_ready,
# 19 attn_global, 20..27 qkv_epoch, 28..35 chunk barrier (mirage's site),
# 36..43 attn_release, 44..47 fused-tail literals, 48..55 chunk barrier
# (fleet's site, 8*NUM_REQS), 56..72 fleet's layer barrier. 44*16 -- the value
# this used to hold, chosen against mirage's map alone -- lands on fleet's
# FUSED_TAIL_MOE_DONE_SLOT, so the QKV epoch and one of the layer body's own
# barriers would share memory and neither could complete.
# Must stay equal to SLOT_QKV_BARRIER_NEW in gpt_oss_120b_kernel.cuh.
SLOT_QKV_BARRIER = 73 * 16  # per-XCD QKV barrier arrival

# Counter buffer
COUNTERS_PER_LAYER = 103 * 16  # 84 base + 10 fused oproj + 9 routing ready


def parse_args():
    parser = argparse.ArgumentParser(description="Fleet MK gpt-oss-120b demo")
    parser.add_argument("--model", default="Gpt/GPT-OSS-120B",
                        help="HuggingFace model name or path")
    parser.add_argument("--model-path", default=None,
                        help="Local model path (overrides --model)")
    parser.add_argument("--prompt", default="Tell me the history of america")
    parser.add_argument("--max-seq-length", type=int, default=512)
    parser.add_argument("--max-new-tokens", type=int, default=None)
    parser.add_argument("--ignore-eos", action="store_true")
    parser.add_argument("--warmup", type=int, default=3)
    parser.add_argument("--fleet-mk-so", default=None,
                        help="Path to compiled gpt_oss_120b.so")
    parser.add_argument("--pytorch-only", action="store_true",
                        help="Use PyTorch for decode (skip fleet_mk kernel)")
    return parser.parse_args()


def load_gpt_oss_120b_kernel(so_path: str):
    """Load the compiled Gpt fleet_mk .so."""
    lib = ctypes.CDLL(so_path)

    lib.gpt_oss_120b_init.restype = None
    lib.gpt_oss_120b_init.argtypes = []

    lib.gpt_oss_120b_launch.restype = None
    lib.gpt_oss_120b_launch.argtypes = [
        ctypes.c_int,       # num_active_tokens
        ctypes.c_float,     # attn_scale
        ctypes.c_void_p,    # cos_ptr
        ctypes.c_void_p,    # sin_ptr
        ctypes.c_void_p,    # qo_indptr
        ctypes.c_void_p,    # kv_indptr
        ctypes.c_void_p,    # kv_indices
        ctypes.c_void_p,    # kv_last_page_len
        ctypes.c_void_p,    # ptr_table
        ctypes.c_void_p,    # counter_buf
        ctypes.c_void_p,    # lm_norm_weight
        ctypes.c_void_p,    # lm_norm_scratch
        ctypes.c_void_p,    # lm_mxfp4_weight
        ctypes.c_void_p,    # lm_bias
        ctypes.c_void_p,    # argmax_output
        ctypes.c_void_p,    # logits_output (bf16 [padded_vocab]; null = argmax only)
        ctypes.c_void_p,    # timing_buf
        ctypes.c_void_p,    # embed_weight
        ctypes.c_int,       # cur_token_id
        ctypes.c_void_p,    # decode_ctrl (GPU pointer to DecodeControl struct)
        ctypes.c_void_p,    # stream
    ]

    lib.gpt_oss_120b_finalize.restype = None
    lib.gpt_oss_120b_finalize.argtypes = []

    # hipGraph-based launch
    lib.gpt_oss_120b_graph_capture.restype = None
    lib.gpt_oss_120b_graph_capture.argtypes = [
        ctypes.c_int,       # num_active_tokens
        ctypes.c_float,     # attn_scale
        ctypes.c_void_p,    # cos_ptr
        ctypes.c_void_p,    # sin_ptr
        ctypes.c_void_p,    # qo_indptr
        ctypes.c_void_p,    # kv_indptr
        ctypes.c_void_p,    # kv_indices
        ctypes.c_void_p,    # kv_last_page_len
        ctypes.c_void_p,    # ptr_table
        ctypes.c_void_p,    # counter_buf
        ctypes.c_void_p,    # lm_norm_weight
        ctypes.c_void_p,    # lm_norm_scratch
        ctypes.c_void_p,    # lm_mxfp4_weight
        ctypes.c_void_p,    # lm_bias
        ctypes.c_void_p,    # argmax_output
        ctypes.c_void_p,    # logits_output (bf16 [padded_vocab]; null = argmax only)
        ctypes.c_void_p,    # timing_buf
        ctypes.c_void_p,    # embed_weight
        ctypes.c_int,       # cur_token_id
        ctypes.c_void_p,    # decode_ctrl
        ctypes.c_void_p,    # stream
        # Zero buffer info
        ctypes.c_void_p,    # counter_buf_raw
        ctypes.c_size_t,    # counter_buf_bytes
        ctypes.c_void_p,    # workspace_buf_raw
        ctypes.c_size_t,    # workspace_buf_bytes
        ctypes.c_void_p,    # moe_barrier_buf_raw
        ctypes.c_size_t,    # moe_barrier_buf_bytes
    ]

    lib.gpt_oss_120b_graph_launch.restype = None
    lib.gpt_oss_120b_graph_launch.argtypes = [
        ctypes.c_int,       # cur_token_id
        ctypes.c_void_p,    # stream
    ]

    lib.gpt_oss_120b_graph_destroy.restype = None
    lib.gpt_oss_120b_graph_destroy.argtypes = []

    # Pipelined graph (bridge + main kernel, no host sync between tokens)
    lib.gpt_oss_120b_pipe_capture.restype = None
    lib.gpt_oss_120b_pipe_capture.argtypes = [
        ctypes.c_int,       # num_active_tokens
        ctypes.c_float,     # attn_scale
        ctypes.c_void_p,    # cos_ptr
        ctypes.c_void_p,    # sin_ptr
        ctypes.c_void_p,    # qo_indptr
        ctypes.c_void_p,    # kv_indptr
        ctypes.c_void_p,    # kv_indices
        ctypes.c_void_p,    # kv_last_page_len
        ctypes.c_void_p,    # ptr_table
        ctypes.c_void_p,    # counter_buf
        ctypes.c_void_p,    # lm_norm_weight
        ctypes.c_void_p,    # lm_norm_scratch
        ctypes.c_void_p,    # lm_mxfp4_weight
        ctypes.c_void_p,    # lm_bias
        ctypes.c_void_p,    # argmax_output
        ctypes.c_void_p,    # logits_output (bf16 [padded_vocab]; null = argmax only)
        ctypes.c_void_p,    # timing_buf
        ctypes.c_void_p,    # embed_weight
        ctypes.c_int,       # cur_token_id
        ctypes.c_void_p,    # decode_ctrl
        ctypes.c_void_p,    # stream
        # Bridge kernel args
        ctypes.c_void_p,    # moe_barrier_raw
        ctypes.c_int,       # moe_barrier_ints
        ctypes.c_void_p,    # cur_token_ptr
        ctypes.c_void_p,    # token_output_buf
        ctypes.c_void_p,    # step_counter
        ctypes.c_int,       # start_pos
        ctypes.c_int,       # page_size
        # Workspace memset
        ctypes.c_void_p,    # workspace_buf_raw
        ctypes.c_size_t,    # workspace_buf_bytes
    ]

    lib.gpt_oss_120b_pipe_launch_first.restype = None
    lib.gpt_oss_120b_pipe_launch_first.argtypes = [ctypes.c_void_p]

    lib.gpt_oss_120b_pipe_launch_step.restype = None
    lib.gpt_oss_120b_pipe_launch_step.argtypes = [ctypes.c_void_p]

    lib.gpt_oss_120b_pipe_launch_all.restype = None
    lib.gpt_oss_120b_pipe_launch_all.argtypes = [ctypes.c_void_p, ctypes.c_int]

    lib.gpt_oss_120b_pipe_destroy.restype = None
    lib.gpt_oss_120b_pipe_destroy.argtypes = []

    # C-side decode loop (eliminates Python per-token overhead)
    lib.gpt_oss_120b_decode_loop.restype = None
    lib.gpt_oss_120b_decode_loop.argtypes = [
        ctypes.c_int,       # num_active_tokens
        ctypes.c_float,     # attn_scale
        ctypes.c_void_p,    # cos_ptr
        ctypes.c_void_p,    # sin_ptr
        ctypes.c_void_p,    # qo_indptr
        ctypes.c_void_p,    # kv_indptr
        ctypes.c_void_p,    # kv_indices
        ctypes.c_void_p,    # kv_last_page_len
        ctypes.c_void_p,    # ptr_table
        ctypes.c_void_p,    # counter_buf
        ctypes.c_void_p,    # lm_norm_weight
        ctypes.c_void_p,    # lm_norm_scratch
        ctypes.c_void_p,    # lm_mxfp4_weight
        ctypes.c_void_p,    # lm_bias
        ctypes.c_void_p,    # argmax_output
        ctypes.c_void_p,    # logits_output (bf16 [padded_vocab]; null = argmax only)
        ctypes.c_void_p,    # timing_buf
        ctypes.c_void_p,    # embed_weight
        ctypes.c_int,       # first_token_id
        ctypes.c_void_p,    # decode_ctrl
        ctypes.c_void_p,    # stream
        # Decode loop params
        ctypes.c_int,       # total_steps
        ctypes.c_int,       # start_pos
        ctypes.c_int,       # page_size
        ctypes.c_void_p,    # token_output_buf (host-pinned)
    ]

    return lib


def main():
    args = parse_args()
    torch.set_default_dtype(torch.bfloat16)

    # -- Load model --
    model_path = args.model_path or args.model
    print(f"Loading gpt-oss-120b from: {model_path}")
    model = AutoModelForCausalLM.from_pretrained(
        model_path,
        dtype=torch.bfloat16,
        device_map="cpu",
        trust_remote_code=True,
    )
    tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)
    model.eval()

    config = model.config
    assert config.hidden_size == ACTUAL_HIDDEN_DIM or config.hidden_size == HIDDEN_SIZE
    assert config.num_attention_heads == NUM_Q_HEADS
    assert config.num_key_value_heads == NUM_KV_HEADS
    assert getattr(config, "head_dim", HEAD_DIM) == HEAD_DIM

    print(f"gpt-oss-120b: {NUM_LAYERS} layers, hidden={HIDDEN_SIZE}, "
          f"moe_intermediate={MOE_INTERMEDIATE_SIZE}, experts={NUM_EXPERTS}, topk={NUM_TOPK}, "
          f"heads={NUM_Q_HEADS}Q/{NUM_KV_HEADS}KV, head_dim={HEAD_DIM}")
    # Printed unconditionally: a packer/.so stride mismatch is silent at runtime,
    # so this line is the only place the packed pitch is visible next to the
    # -DMPK_MOE_K_STRIDE the kernel was built with.
    print(f"MoE expert rows: stride={MOE_K_STRIDE} values "
          f"({MOE_K_STRIDE // 2} B), reduction={HIDDEN_SIZE} values "
          f"({HIDDEN_SIZE // 128} MFMA iters)"
          + ("" if MOE_K_STRIDE == HIDDEN_SIZE else
             "  <-- .so MUST be built -DMPK_MOE_K_STRIDE=%d" % MOE_K_STRIDE))
    print(f"MoE scales: {'SPLIT [all data][all scales]' if MOE_SPLIT_SCALES else 'interleaved per workgroup'}"
          + ("  <-- .so MUST be built -DMPK_MOE_SPLIT_SCALES=1" if MOE_SPLIT_SCALES else ""))
    print(f"MoE expert pitch: W13 {W13_N_STRIDE} rows stored / {W13_OUTPUT_SIZE} "
          f"computed, W2 {W2_N_STRIDE} / {HIDDEN_SIZE}"
          + ("" if not MOE_N_STRIDE else
             "  <-- .so MUST be built -DMPK_MOE_N_STRIDE=%d" % MOE_N_STRIDE))
    # No .so flag for this one: the kernel already takes the two bases as
    # separate arguments and never assumes a relationship between them.
    print("MoE buffers: "
          + ("SEPARATE allocations for data and scales" if MOE_SPLIT_BUFFERS
             else "one allocation"))

    bs = 1  # decode batch size
    page_size = 16  # == fleet_mk PAGE_SIZE (vLLM's ROCm default block size)
    # Enough pages to hold the whole sequence. This used to be a bare 16, which
    # only worked because page_size was 128 (16 x 128 = 2048 entries, far past
    # any --max-seq-length). At page_size 16 a fixed 16 pages is 256 entries and
    # silently truncates the default 512-token run, so derive it instead.
    max_num_pages = (args.max_seq_length + page_size - 1) // page_size

    # -- Tokenize --
    if hasattr(tokenizer, 'chat_template') and tokenizer.chat_template:
        messages = [{"role": "user", "content": args.prompt}]
        formatted = tokenizer.apply_chat_template(
            messages, tokenize=False, add_generation_prompt=True)
        model_inputs = tokenizer([formatted], return_tensors="pt",
                                  add_special_tokens=False).to("cuda")
    else:
        model_inputs = tokenizer([args.prompt], return_tensors="pt").to("cuda")

    tokens = torch.zeros(args.max_seq_length, dtype=torch.long, device="cuda")
    prompt_ids = model_inputs.input_ids[0]
    prompt_len = prompt_ids.shape[0]
    tokens[:prompt_len] = prompt_ids
    print(f"Prompt: {prompt_len} tokens, max_seq_length: {args.max_seq_length}")

    # -- RoPE position embeddings --
    rotary_emb = model.model.rotary_emb
    positions = torch.arange(args.max_seq_length, device="cuda").unsqueeze(0)
    cos_raw, sin_raw = rotary_emb(
        torch.ones(1, 1, device="cuda"), positions)
    cos_raw = cos_raw[0]  # [max_seq, head_dim]
    sin_raw = sin_raw[0]
    if cos_raw.shape[-1] < HEAD_DIM:
        cos_raw = torch.nn.functional.pad(cos_raw, (0, HEAD_DIM - cos_raw.shape[-1]))
        sin_raw = torch.nn.functional.pad(sin_raw, (0, HEAD_DIM - sin_raw.shape[-1]))
    cos_padded = cos_raw.contiguous()
    sin_padded = sin_raw.contiguous()

    # -- Pack weights --
    print("Packing MXFP4 weights...")
    weight_tensors = []  # keep refs to prevent GC
    # MoE scale sections, one entry per layer, when they live in their own
    # allocation. Kept out of weight_tensors because that list is indexed by a
    # fixed WEIGHTS_PER_LAYER stride the pointer table depends on; these are
    # optional and would shift every slot after them. None when unused.
    moe_w13_scales = []
    moe_w2_scales = []

    # Load safetensors index for direct MXFP4 expert weight access
    # (HuggingFace dequantizes to bf16 without Triton -- we bypass that)
    _st_index_path = os.path.join(model_path, "model.safetensors.index.json")
    with open(_st_index_path) as _f:
        _st_index = json.load(_f)["weight_map"]
    _st_file_cache = {}  # cache open safetensor file handles
    def _load_st_tensor(name):
        fname = _st_index[name]
        fpath = os.path.join(model_path, fname)
        if fpath not in _st_file_cache:
            _st_file_cache[fpath] = safe_open(fpath, framework="pt")
        return _st_file_cache[fpath].get_tensor(name)

    for li in range(NUM_LAYERS):
        layer = model.model.layers[li]

        # -- QKV weight: interleave Q/K/V by KV groups --
        w_q = pad_weight_2d(layer.self_attn.q_proj.weight.data.to("cuda"),
                            target_cols=HIDDEN_SIZE)
        w_k = pad_weight_2d(layer.self_attn.k_proj.weight.data.to("cuda"),
                            target_cols=HIDDEN_SIZE)
        w_v = pad_weight_2d(layer.self_attn.v_proj.weight.data.to("cuda"),
                            target_cols=HIDDEN_SIZE)

        qkv_chunks = []
        for g in range(NUM_KV_HEADS):
            qkv_chunks.append(w_q[g * Q_PER_KV * HEAD_DIM:(g + 1) * Q_PER_KV * HEAD_DIM])
            qkv_chunks.append(w_k[g * HEAD_DIM:(g + 1) * HEAD_DIM])
            qkv_chunks.append(w_v[g * HEAD_DIM:(g + 1) * HEAD_DIM])
        w_qkv = torch.cat(qkv_chunks, dim=0).contiguous()
        assert w_qkv.shape == (QKV_OUTPUT_SIZE, HIDDEN_SIZE), \
            f"QKV shape mismatch: {w_qkv.shape} vs ({QKV_OUTPUT_SIZE}, {HIDDEN_SIZE})"

        qkv_blocks, qkv_scales = quantize_bf16_to_mxfp4(w_qkv)
        qkv_packed = pack_mxfp4_workgroup(
            qkv_blocks, qkv_scales, output_per_wg=OUTPUT_PER_WG,
            target_out_dim=QKV_OUTPUT_SIZE,
            target_num_blocks=HIDDEN_SIZE // 32)
        weight_tensors.append(qkv_packed)  # [0] qkv_weight

        # QKV bias
        qkv_bias = torch.zeros(QKV_OUTPUT_SIZE, dtype=torch.bfloat16, device="cuda")
        if layer.self_attn.q_proj.bias is not None:
            q_bias = layer.self_attn.q_proj.bias.data.to("cuda")
            k_bias = layer.self_attn.k_proj.bias.data.to("cuda")
            v_bias = layer.self_attn.v_proj.bias.data.to("cuda")
            bias_chunks = []
            for g in range(NUM_KV_HEADS):
                bias_chunks.append(q_bias[g * Q_PER_KV * HEAD_DIM:(g + 1) * Q_PER_KV * HEAD_DIM])
                bias_chunks.append(k_bias[g * HEAD_DIM:(g + 1) * HEAD_DIM])
                bias_chunks.append(v_bias[g * HEAD_DIM:(g + 1) * HEAD_DIM])
            qkv_bias = torch.cat(bias_chunks, dim=0).contiguous()
        weight_tensors.append(qkv_bias)  # [1] qkv_bias

        # -- O-proj weight (OPW=16, per-XCD partitioned) --
        w_o = pad_weight_2d(layer.self_attn.o_proj.weight.data.to("cuda"),
                            target_rows=HIDDEN_SIZE)
        o_blocks, o_scales = quantize_bf16_to_mxfp4(w_o)
        o_packed = pack_mxfp4_workgroup(
            o_blocks, o_scales, output_per_wg=OPROJ_OPW,
            target_out_dim=HIDDEN_SIZE,
            target_num_blocks=OPROJ_REDUCTION // 32)
        weight_tensors.append(o_packed)  # [2] oproj_weight (OPW=16)

        # O-proj bias (zeros)
        o_bias = torch.zeros(HIDDEN_SIZE, dtype=torch.bfloat16, device="cuda")
        if layer.self_attn.o_proj.bias is not None:
            o_raw = layer.self_attn.o_proj.bias.data.to("cuda")
            o_bias[:o_raw.shape[0]] = o_raw
        weight_tensors.append(o_bias)  # [3] oproj_bias

        # -- RMSNorm weights (pad to HIDDEN_SIZE if needed) --
        norm_w1 = torch.zeros(HIDDEN_SIZE, dtype=torch.bfloat16, device="cuda")
        norm_w1_raw = layer.input_layernorm.weight.data.to("cuda")
        norm_w1[:norm_w1_raw.shape[0]] = norm_w1_raw
        weight_tensors.append(norm_w1.contiguous())  # [4] norm_weight_pre

        norm_w2 = torch.zeros(HIDDEN_SIZE, dtype=torch.bfloat16, device="cuda")
        norm_w2_raw = layer.post_attention_layernorm.weight.data.to("cuda")
        norm_w2[:norm_w2_raw.shape[0]] = norm_w2_raw
        weight_tensors.append(norm_w2.contiguous())  # [5] norm_weight_post

        # -- Router weight --
        w_router = pad_weight_2d(layer.mlp.router.weight.data.to("cuda"),
                                 target_cols=HIDDEN_SIZE)
        r_blocks, r_scales = quantize_bf16_to_mxfp4(w_router)
        r_packed = pack_mxfp4_workgroup(
            r_blocks, r_scales, output_per_wg=OUTPUT_PER_WG,
            target_out_dim=ROUTER_OUTPUT_SIZE,
            target_num_blocks=HIDDEN_SIZE // 32)
        weight_tensors.append(r_packed)  # [6] router_weight (MXFP4)

        # Router bias (padded to ROUTER_OUTPUT_SIZE)
        r_bias = torch.zeros(ROUTER_OUTPUT_SIZE, dtype=torch.bfloat16, device="cuda")
        r_bias_raw = layer.mlp.router.bias.data.to("cuda")
        r_bias[:r_bias_raw.shape[0]] = r_bias_raw
        weight_tensors.append(r_bias)  # [7] router_bias

        # BF16 router weight for fused GEMV (padded to HIDDEN_SIZE columns)
        w_router_bf16 = pad_weight_2d(layer.mlp.router.weight.data.to("cuda"),
                                       target_cols=HIDDEN_SIZE)
        weight_tensors.append(w_router_bf16.contiguous())  # [8] router_weight_bf16

        # -- Per-expert W13 (gate+up) weights --
        # Load MXFP4 blocks+scales directly from safetensors (bypasses Triton dequant)
        gu_blocks = _load_st_tensor(f"model.layers.{li}.mlp.experts.gate_up_proj_blocks").to("cuda")
        gu_scales = _load_st_tensor(f"model.layers.{li}.mlp.experts.gate_up_proj_scales").to("cuda")
        gu_common = dict(
            output_per_wg=W13_OPW,
            target_out_dim=W13_OUTPUT_SIZE,
            target_num_blocks=HIDDEN_SIZE // 32,
            row_stride_blocks=MOE_K_STRIDE_BLOCKS,
            out_stride_rows=W13_N_STRIDE if MOE_N_STRIDE else None,
            split_scales=MOE_SPLIT_SCALES)
        # In split-buffer mode the two sections are packed as two independent
        # allocations rather than one. Same bytes in the same within-section
        # order either way -- `section` partitions the buffer, it does not
        # recompute it (tools/check_pack_section.py property 2).
        gu_packed = pack_mxfp4_workgroup(
            gu_blocks, gu_scales,
            section="data" if MOE_SPLIT_BUFFERS else "both", **gu_common)
        weight_tensors.append(gu_packed)  # [9] w13_weight [E, w13_n_wgs, wg_bytes]
        moe_w13_scales.append(pack_mxfp4_workgroup(
            gu_blocks, gu_scales, section="scales", **gu_common)
            if MOE_SPLIT_BUFFERS else None)
        del gu_blocks, gu_scales

        # W13 bias [E, 2*intermediate]
        w13_bias = pad_weight_2d(layer.mlp.experts.gate_up_proj_bias.data.to("cuda"),
                                 target_cols=W13_OUTPUT_SIZE)
        weight_tensors.append(w13_bias)  # [10] w13_bias

        # -- Per-expert W2 (down) weights --
        dp_blocks = _load_st_tensor(f"model.layers.{li}.mlp.experts.down_proj_blocks").to("cuda")
        dp_scales = _load_st_tensor(f"model.layers.{li}.mlp.experts.down_proj_scales").to("cuda")
        dp_common = dict(
            output_per_wg=W2_OPW,
            target_out_dim=HIDDEN_SIZE,
            target_num_blocks=MOE_INTERMEDIATE_SIZE // 32,
            row_stride_blocks=MOE_K_STRIDE_BLOCKS,
            out_stride_rows=W2_N_STRIDE if MOE_N_STRIDE else None,
            split_scales=MOE_SPLIT_SCALES)
        dp_packed = pack_mxfp4_workgroup(
            dp_blocks, dp_scales,
            section="data" if MOE_SPLIT_BUFFERS else "both", **dp_common)
        weight_tensors.append(dp_packed)  # [11] w2_weight [E, w2_n_wgs, wg_bytes]
        moe_w2_scales.append(pack_mxfp4_workgroup(
            dp_blocks, dp_scales, section="scales", **dp_common)
            if MOE_SPLIT_BUFFERS else None)
        del dp_blocks, dp_scales

        # W2 bias [E, hidden]
        w2_bias = pad_weight_2d(layer.mlp.experts.down_proj_bias.data.to("cuda"),
                                target_cols=HIDDEN_SIZE)
        weight_tensors.append(w2_bias)  # [12] w2_bias

        # -- Per-head attention sinks [num_q_heads] bf16 (GPT-OSS specific) --
        # merge_splitkv indexes as sinks[kv_head_idx * NUM_Q_PER_KV + head_idx],
        # which matches the natural [num_q_heads] ordering.
        w_sinks = layer.self_attn.sinks.data.to("cuda").to(torch.bfloat16).contiguous()
        assert w_sinks.shape == (NUM_Q_HEADS,), f"sinks shape {w_sinks.shape}"
        weight_tensors.append(w_sinks)  # [13] attn_sinks

        # Free layer refs
        del w_q, w_k, w_v, w_qkv, w_o
        del layer

        gc.collect()
        torch.cuda.empty_cache()

        if (li + 1) % 6 == 0 or li == NUM_LAYERS - 1:
            print(f"  Packed layer {li + 1}/{NUM_LAYERS}")

    WEIGHTS_PER_LAYER = 14
    assert len(weight_tensors) == NUM_LAYERS * WEIGHTS_PER_LAYER
    _st_file_cache.clear()  # close safetensor file handles

    weight_ptrs_host = [t.data_ptr() for t in weight_tensors]

    # Diagnostic tail pad: see FLEET_MK_MOE_TAIL_PAD. Appended AFTER data_ptr() is
    # taken, so every base and every section offset is byte-for-byte what it was
    # -- the pad exists only to make the addresses past the last scale byte
    # legal. Held in weight_tensors' shadow by this list so it is not collected.
    _moe_tail_pads = []
    if MOE_TAIL_PAD:
        _extra = 0 if MOE_TAIL_PAD < 0 else MOE_TAIL_PAD
        for li in range(NUM_LAYERS):
            for slot in (9, 11):  # w13_weight, w2_weight
                if MOE_TAIL_PAD_SLOT == "w13" and slot != 9:
                    continue
                if MOE_TAIL_PAD_SLOT == "w2" and slot != 11:
                    continue
                t = weight_tensors[li * WEIGHTS_PER_LAYER + slot]
                padded = torch.empty(t.numel() + _extra,
                                     dtype=t.dtype, device=t.device)
                padded[:t.numel()] = t.reshape(-1)
                padded[t.numel():] = 0
                _moe_tail_pads.append(padded)
                weight_ptrs_host[li * WEIGHTS_PER_LAYER + slot] = padded.data_ptr()
        print(f"MoE slab tail pad: {MOE_TAIL_PAD} B appended per expert slab "
              f"(DIAGNOSTIC -- hides overruns, does not fix them)")

    # -- Embedding + LM head --
    embed_weight = model.model.embed_tokens.weight.data.to("cuda")
    final_norm_w_raw = model.model.norm.weight.data.to("cuda")
    final_norm_w = torch.zeros(HIDDEN_SIZE, dtype=torch.bfloat16, device="cuda")
    final_norm_w[:final_norm_w_raw.shape[0]] = final_norm_w_raw
    final_norm_w = final_norm_w.contiguous()

    lm_head_weight = pad_weight_2d(
        model.lm_head.weight.data.to("cuda"),
        target_rows=PADDED_VOCAB_SIZE,
        target_cols=HIDDEN_SIZE)
    lm_blocks, lm_scales = quantize_bf16_to_mxfp4(lm_head_weight)
    lm_head_packed = pack_mxfp4_workgroup(
        lm_blocks, lm_scales, output_per_wg=OUTPUT_PER_WG,
    ).squeeze(0)
    print(f"LM head MXFP4: {lm_head_weight.shape} -> {lm_head_packed.shape}")
    lm_head_zero_bias = torch.zeros(1, PADDED_VOCAB_SIZE, dtype=torch.bfloat16, device="cuda")

    # -- Allocate workspace buffers --
    print("Allocating buffers...")
    q_ws_stride = Q_PER_KV * HEAD_DIM  # 512
    kv_cache_stride = NUM_KV_HEADS * HEAD_DIM  # 512

    # Per-layer KV cache (paged)
    num_kv_entries = max_num_pages * page_size
    buf_k_cache = [torch.zeros(num_kv_entries, kv_cache_stride,
                                dtype=torch.bfloat16, device="cuda") for _ in range(NUM_LAYERS)]
    buf_v_cache = [torch.zeros(num_kv_entries, kv_cache_stride,
                                dtype=torch.bfloat16, device="cuda") for _ in range(NUM_LAYERS)]

    # Residual buffer (embedding goes here, then oproj_out serves as residual for layers 1+)
    buf_residual = torch.zeros(bs, HIDDEN_SIZE, dtype=torch.bfloat16, device="cuda")
    # x_output: QKV writes ResAdd+RMSNorm result here (separate from residual, like mirage's mlp_weighted_sum_out)
    buf_x_output = torch.zeros(bs, HIDDEN_SIZE, dtype=torch.bfloat16, device="cuda")

    # Norm scratch buffers
    buf_norm_scratch1 = torch.zeros(bs, HIDDEN_SIZE, dtype=torch.bfloat16, device="cuda")
    buf_norm_scratch2 = torch.zeros(bs, HIDDEN_SIZE, dtype=torch.bfloat16, device="cuda")

    # QKV output
    buf_qkv_output = torch.zeros(bs, QKV_OUTPUT_SIZE, dtype=torch.bfloat16, device="cuda")

    # Attention buffers
    buf_q_workspace = torch.zeros(bs, NUM_Q_HEADS * HEAD_DIM, dtype=torch.bfloat16, device="cuda")
    buf_attn_out = torch.zeros(bs, NUM_Q_HEADS * HEAD_DIM, dtype=torch.bfloat16, device="cuda")

    # O-proj output
    buf_oproj_out = torch.zeros(bs, HIDDEN_SIZE, dtype=torch.bfloat16, device="cuda")

    # MoE routing buffers
    buf_routing_indices = torch.zeros(NUM_EXPERTS, bs, dtype=torch.int32, device="cuda")
    buf_topk_weight = torch.zeros(bs, NUM_TOPK, dtype=torch.float32, device="cuda")
    buf_active_expert_ids = torch.zeros(NUM_EXPERTS + 1, dtype=torch.int32, device="cuda")

    # MoE intermediate buffers
    buf_swiglu_out = torch.zeros(bs, NUM_TOPK, MOE_INTERMEDIATE_SIZE, dtype=torch.bfloat16, device="cuda")
    # MOE_WS_SLOTS slabs per token, not one. Fleet's MoE W2 epilogue writes to
    # (b * MOE_WS_SLOTS + slot) * HIDDEN_SIZE: a token routes to exactly
    # NUM_TOPK experts, topk_slot is known per tile, and wg_idx partitions the
    # hidden axis, so (token, slot, hidden range) has exactly one writer and the
    # float atomicAdd becomes a plain write-through store. That removes the
    # accumulation-order dependence that made decode non-deterministic.
    # The kernel writes 4x this stride whether or not this line is widened, so a
    # narrow buffer here corrupts silently -- it still compiles and links.
    MOE_WS_SLOTS = NUM_TOPK  # must match kernel::MOE_WS_SLOTS (moe_ws_layout.cuh)
    buf_moe_workspace_f32 = torch.zeros(bs, MOE_WS_SLOTS * HIDDEN_SIZE,
                                        dtype=torch.float32, device="cuda")

    # MoE per-expert barrier. 160 ints (10 cache lines) per expert, NOT 16.
    #
    # Fleet's kernel indexes this as MOE_BAR_STRIDE = MOE_BAR_SLOTS(10) *
    # MOE_BAR_LINE(16) ints per expert: 8 per-XCD release flags, then the global
    # arrival counter on line 8. At 16 ints/expert every expert past the first
    # aliases the next one's flags, and the arrival counter at line 8 lands
    # outside the allocation entirely.
    #
    # The one-line-per-slot spacing is a correctness requirement, not padding.
    # Fleet's own note (gang_moe_fused_mxfp4_mi300.cuh, above the atomic at
    # :2412): the release fan-out uses st_wt (sc0 sc1), which bypasses L2 and
    # goes straight to HBM, while the arrival counter is an L2-resident atomic
    # RMW. Sharing a 64-byte line lets the stale L2 copy be written back over
    # fresh write-through release values, silently reverting releases that
    # already fired.
    #
    # NOT zeroed between decode iterations, and the in-kernel zeroing loop is
    # compiled out under the fleet layer body. The W13->W2 release value is
    # `layer_idx + 1` on a counter fleet never resets, so wiping it destroys the
    # ordering it encodes. Measured: with the per-layer counter block already
    # shared, zeroing this left every XCD parked at
    #   phase=80 layer=1 barrier=800..803 observed=0 expected=2
    # -- fleet's MoE W13->W2 barrier at layer 1, waiting for the 2 that layer
    # 0's release wrote and the zeroing erased.
    MOE_BAR_STRIDE = 160  # must equal kernel::MOE_BAR_SLOTS * kernel::MOE_BAR_LINE
    buf_moe_barrier = torch.zeros(MOE_BAR_STRIDE * NUM_EXPERTS,
                                  dtype=torch.int32, device="cuda")

    # Counter buffer — monotonic counters, NO need to zero between iterations
    # Layout: [per-layer counters | rank counters | decode iter counter | embed barrier]
    RANK_COUNTER_INTS = NUM_XCDS * 16
    DECODE_ITER_COUNTER_INTS = 16  # 1 cache line for decode iteration barrier
    # Embedding-write barrier: 1 global cache line + NUM_XCDS per-XCD lines.
    # Kept outside the per-layer blocks, whose 103 cache lines are fully used.
    # Must match SLOT_EMBED_DONE / SLOT_EMBED_LOCAL in the kernel.
    EMBED_BARRIER_INTS = (1 + NUM_XCDS) * 16
    # Slack for the FLEET_MK_ILB_TIMING diagnostic probe barrier (compiled out in
    # production). Always allocated so a timing build needs no Python change.
    ILB_PROBE_INTS = 20 * 16
    counter_total_ints = (NUM_LAYERS * COUNTERS_PER_LAYER + RANK_COUNTER_INTS
                          + DECODE_ITER_COUNTER_INTS + EMBED_BARRIER_INTS
                          + ILB_PROBE_INTS)
    buf_counter = torch.zeros(counter_total_ints, dtype=torch.int32, device="cuda")

    # Logits scratch for fused OProj+Router+TopK kernel
    buf_logits_scratch = torch.zeros(bs, NUM_EXPERTS, dtype=torch.bfloat16, device="cuda")

    # Attention split-KV buffers
    o_acc_dim = NUM_KV_HEADS * NUM_KV_CHUNKS * Q_PER_KV * HEAD_DIM
    buf_o_acc_f32 = torch.zeros(bs, o_acc_dim, dtype=torch.float32, device="cuda")
    lse_dim = NUM_KV_HEADS * NUM_KV_CHUNKS * Q_PER_KV
    buf_lse_acc = torch.zeros(bs, lse_dim, dtype=torch.float32, device="cuda")

    # LM head buffers
    buf_argmax_out = torch.zeros(1, dtype=torch.int64, device="cuda")
    buf_lm_norm_scratch = torch.zeros(bs, HIDDEN_SIZE, dtype=torch.bfloat16, device="cuda")

    # Counter buffer is a view into buf_merged_counters (allocated above with MoE barrier)

    # Subphase timing buffer (12 slots per layer + 4 tail slots)
    TIMING_SLOTS_PER_LAYER = 14
    TIMING_TAIL_SLOTS = 4
    timing_total = NUM_LAYERS * TIMING_SLOTS_PER_LAYER + TIMING_TAIL_SLOTS
    buf_timing = torch.zeros(timing_total, dtype=torch.int64, device="cuda")

    # Debug: workspace snapshot buffer for layer 0

    # -- Build pointer table --
    # Layout: ptr_table[xcd * NUM_LAYERS * PTRS_PER_LAYER + layer * PTRS_PER_LAYER + slot]
    print("Building pointer table...")

    ptr_table_host = []
    for xcd in range(NUM_XCDS):
        for li in range(NUM_LAYERS):
            base = li * WEIGHTS_PER_LAYER
            qkv_weight_base = weight_ptrs_host[base + 0]
            qkv_bias = weight_ptrs_host[base + 1]
            oproj_weight_base = weight_ptrs_host[base + 2]
            oproj_bias = weight_ptrs_host[base + 3]
            norm_w1 = weight_ptrs_host[base + 4]
            norm_w2 = weight_ptrs_host[base + 5]
            router_weight_base = weight_ptrs_host[base + 6]
            router_bias = weight_ptrs_host[base + 7]
            router_weight_bf16 = weight_ptrs_host[base + 8]
            w13_weight_base = weight_ptrs_host[base + 9]
            w13_bias = weight_ptrs_host[base + 10]
            w2_weight_base = weight_ptrs_host[base + 11]
            w2_bias = weight_ptrs_host[base + 12]
            attn_sinks = weight_ptrs_host[base + 13]

            # Per-XCD weight offsets
            qkv_weight_xcd = qkv_weight_base + xcd * QKV_N_WGS_PER_XCD * QKV_WG_BYTES

            # Fleet's QKV weight prefetch hand-off (input_ptrs[24]/[25]).
            #
            # Fleet stages the NEXT layer's QKV weight tile from HBM into LDS
            # during the cross-XCD barrier spin at the end of this layer, when
            # the memory system is otherwise idle. Two pointers drive it:
            #
            #   [24] what to stage = next layer's per-XCD QKV weight. Null on
            #        the last layer: fleet's own comment at :1690 says nothing
            #        may be staged across the iteration boundary, because the
            #        buffer the next iteration reads is not yet published.
            #   [25] whether this layer's tile was already staged. Fleet gates
            #        on `input_ptrs[25] == input_ptrs[4]` (:458) and passes the
            #        result as weights_preloaded, which tells the QKV GEMM to
            #        skip its own DMA and just drain. So [25] must be THIS
            #        layer's own qkv_weight_xcd when the previous layer staged
            #        it, and anything unequal otherwise -- null on layer 0,
            #        which has no previous layer.
            #
            # The per-XCD offset matters: the prefetching worker passes its own
            # xcd_rank as tile_idx, and xcd_rank is stable across layers, so it
            # stages exactly the tile it will itself execute next layer. Handing
            # it the unoffset base would stage XCD 0's tile for all eight.
            next_qkv_weight_xcd = 0
            if li + 1 < NUM_LAYERS:
                next_qkv_weight_xcd = (
                    weight_ptrs_host[(li + 1) * WEIGHTS_PER_LAYER + 0]
                    + xcd * QKV_N_WGS_PER_XCD * QKV_WG_BYTES)
            prefetched_qkv_weight_xcd = qkv_weight_xcd if li > 0 else 0
            # QKV bias per-XCD (10 tiles * 64 = 640 bf16 per XCD)
            qkv_bias_xcd = qkv_bias + xcd * QKV_N_WGS_PER_XCD * OUTPUT_PER_WG * 2  # bf16 = 2 bytes
            # OProj weight per-XCD partitioned (OPW=16, 23 tiles/XCD)
            oproj_weight_xcd = oproj_weight_base + xcd * OPROJ_N_WGS_PER_XCD * OPROJ_WG_BYTES
            # OProj bias per-XCD (23 tiles * 16 = 368 bf16 per XCD)
            oproj_bias_xcd = oproj_bias + xcd * OPROJ_N_WGS_PER_XCD * OPROJ_OPW * 2  # bf16 = 2 bytes
            # Note: OProj residual per-XCD offset computed at runtime in the kernel
            # Router BF16 weight per-XCD (16 experts per XCD, each row = HIDDEN_SIZE bf16)
            router_tile_n = NUM_EXPERTS // NUM_XCDS  # 16
            router_bf16_xcd = router_weight_bf16 + xcd * router_tile_n * HIDDEN_SIZE * 2  # bf16 = 2 bytes
            # Router bias per-XCD (16 experts per XCD)
            router_bias_xcd = router_bias + xcd * router_tile_n * 2  # bf16 = 2 bytes
            # Logits scratch per-XCD (16 experts per XCD)
            logits_scratch_xcd = buf_logits_scratch.data_ptr() + xcd * router_tile_n * 2  # bf16

            # MoE scale bases. NOT per-XCD: every XCD runs every expert, so
            # unlike qkv/oproj there is nothing to partition here.
            #
            # In split mode the slab is [all data][all scales] in one
            # allocation, so the scale section starts one full data region past
            # the base -- the same arithmetic the kernel used to do internally,
            # moved to the host now that the kernel takes the base as an
            # argument. In interleaved mode there IS no scale section, and these
            # resolve to the data base: a mapped address the kernel never
            # dereferences, rather than a null or a stale value that would fault
            # confusingly if the knobs ever disagreed.
            #
            # Under split BUFFERS the scale section is its own allocation and
            # there is no arithmetic at all -- which is the arrangement that lets
            # the data pointer belong to someone else entirely.
            if MOE_SPLIT_BUFFERS:
                w13_scale_base = moe_w13_scales[li].data_ptr()
                w2_scale_base = moe_w2_scales[li].data_ptr()
            else:
                w13_scale_base = w13_weight_base + (
                    NUM_EXPERTS * W13_EXPERT_BYTES if MOE_SPLIT_SCALES else 0)
                w2_scale_base = w2_weight_base + (
                    NUM_EXPERTS * W2_EXPERT_BYTES if MOE_SPLIT_SCALES else 0)

            # Counter buffer. ONE block shared by every layer -- NOT `+ li *
            # COUNTERS_PER_LAYER`, which is what this used to be.
            #
            # Fleet's layer body derives every barrier's release value from the
            # layer index rather than snapshotting a shared counter:
            #     layer_counter = task_layer_idx
            #     qkv_epoch_expected = attn_release_expected = layer_counter + 1
            # and its counters are monotonic, never reset (fleet allocates a
            # single `oproj_topk_counters` tensor and passes that same tensor at
            # every call site; see fleet demo/gpt_oss/demo.py:1235,1615,1685).
            # Layer L therefore waits for its epoch counter to reach L+1, having
            # been left at L by layer L-1 *in the same memory*.
            #
            # Giving each layer its own zeroed block breaks exactly that. Layer
            # 2's counter starts at 0, one arrival takes it to 1, and every
            # worker waits forever for 2. That is not a hypothesis: with
            # -DFLEET_MK_WORKER_STATE the mid-hang dump reads
            #   xcd=* phase=20 layer=2 barrier=20 observed=1 expected=2 -> 10 workers
            #   xcd=* phase=60 layer=2 barrier=60 observed=0 expected=2 -> 20 workers
            # on all 8 XCDs -- fleet's Phase 2 QKV epoch and Phase 6 attn
            # release, short by precisely the arrivals the previous layer would
            # have contributed had it shared the block.
            #
            # The per-layer stride was correct for fleet_mk's OWN barriers, which
            # zero and reuse their slots; it is incompatible with fleet's
            # monotonic-counter contract. Sharing one block is what fleet does.
            counter_ptr = buf_counter.data_ptr()

            # Mirage buffer layout (no ping-pong):
            #   output_ptrs[0] = buf_x_output (separate QKV intermediate, like mirage's mlp_weighted_sum_out)
            #   output_ptrs[5] = buf_oproj_out (residual after OProj, shared across all layers)
            #   input_ptrs[1]  = buf_residual for layer 0, buf_oproj_out for layers 1+

            # Pre-computed mirage format: 26 mirage_in + 11 mirage_out + 1 counter = 38 ptrs
            # Eliminates all conditional remapping in the kernel.
            qkv_barrier_ptr = counter_ptr + SLOT_QKV_BARRIER * 4  # byte offset

            mirage_in = [
                buf_moe_workspace_f32.data_ptr(),  # [0]  workspace_f32
                buf_residual.data_ptr() if li == 0 else buf_oproj_out.data_ptr(),  # [1] residual
                norm_w1,                           # [2]  norm_weight_pre
                buf_norm_scratch1.data_ptr(),      # [3]  norm_scratch_pre
                qkv_weight_xcd,                    # [4]  qkv_weight
                qkv_bias_xcd,                      # [5]  qkv_bias
                attn_sinks,                        # [6]  attn_sinks (per-layer, bf16)
                qkv_barrier_ptr,                   # [7]  qkv_barrier
                buf_lse_acc.data_ptr(),             # [8]  lse_acc
                oproj_weight_xcd,                  # [9]  oproj_weight
                oproj_bias_xcd,                    # [10] oproj_bias
                norm_w2,                           # [11] norm_weight_post
                buf_norm_scratch2.data_ptr(),      # [12] norm_scratch_post
                router_bf16_xcd,                   # [13] router_weight (bf16 per-XCD)
                router_bias_xcd,                   # [14] router_bias (per-XCD)
                logits_scratch_xcd,                # [15] logits_scratch (per-XCD)
                counter_ptr,                       # [16] oproj_counters (counter base)
                w13_weight_base,                   # [17] moe_gate_up_weight
                w2_weight_base,                    # [18] moe_down_weight
                w13_bias,                          # [19] moe_w13_bias
                w2_bias,                           # [20] moe_w2_bias
                buf_moe_barrier.data_ptr(),        # [21] moe_barrier
                buf_swiglu_out.data_ptr(),         # [22] moe_swiglu_out
                buf_o_acc_f32.data_ptr(),           # [23] o_acc_f32
                # [24]/[25] -- FLEET'S QKV-PREFETCH HAND-OFF.
                #
                # These used to carry fleet_mk's MoE scale bases, which was a real
                # collision and the root cause of the "+1.09 ms dual-body
                # penalty". Fleet reads these two slots at exactly five sites
                # (gang_full_layer_fused_mi300.cuh :458, :1693, :1719, :1912,
                # :1917) and every one of them is the QKV weight prefetch --
                # see the block above the loop where these are computed.
                #
                # Nothing on the MoE side wants them: fleet's MoE call site
                # (:1259-1271) passes input_ptrs[12,17,18,19,20,21,22] only,
                # and gang_moe_fused_mxfp4_kernel_mi300 takes 12 parameters
                # with no scale pointers at all -- it reads MXFP4 scales inline
                # from the packed slab. MPK_MOE_SPLIT_SCALES has ZERO
                # occurrences in fleet's tree, so fleet_mk's -D for it was already
                # being silently ignored. The scale bases are still computed
                # above because the non-fleet build path passes them; under
                # fleet's header they simply have no consumer.
                #
                # What the old values did: slot 24 was a valid non-null address,
                # so the staging DMA fired on all 36 layers and pulled MoE scale
                # bytes into the QKV LDS region, while slot 25 never equalled
                # slot 4, so weights_preloaded stayed false and QKV re-read from
                # HBM anyway. Full cost, zero benefit.
                #
                # MEASURED, A/B on ONE .so with only these two integers changed
                # (-DMPK_ENABLE_DEVICE_TASK_TIMING, medians over 126144 phase
                # lines each, tools/fused_phase_stats.py --compare):
                #
                #     phase          collided    fixed    delta
                #     qkv_gemm         15.40     13.50    -1.90
                #     qkv_attn         22.00     20.20    -1.80
                #     xcd_barrier     225.30    218.10    -7.20
                #     moe              45.60     45.60     0.00
                #     total           312.40    303.50    -8.90
                #
                # End to end that is ~11 us/token (layers 3390.5 -> 3379.7 us,
                # non-timing build), text coherent, next_token=35644 on iter 1.
                #
                # NOTE WHAT THIS REFUTES. The collision was written up as the
                # root cause of the "+1.09 ms dual-body penalty", on the theory
                # that the bogus DMA was polluting both weight-staging phases.
                # It is not: moe moves 0.00 us. The prefetch is real and worth
                # having, but it is a ~11 us/token effect, two orders of
                # magnitude short of 1.09 ms. The dual-body cost remains
                # unexplained -- see dual-layer-body-cost.md, and do not treat
                # this as having closed it.
                #
                # NEGATIVE RESULT, superseded but recorded: nulling both slots
                # appeared to fail 3 runs of 3. That verdict was invalid. Those
                # runs carried FLEET_MK_MOE_SPLIT_SCALES/K_STRIDE/N_STRIDE env
                # values against a .so built WITHOUT the matching -D flags, and
                # that mismatch faults deterministically at iter 1 (next_token
                # =-1, HIP error 700) on the shipping .so too. The knobs and the
                # build flags must agree; the demo prints both for exactly this
                # reason.
                (next_qkv_weight_xcd if FLEET_MK_QKV_PF else w13_scale_base),  # [24]
                (prefetched_qkv_weight_xcd if FLEET_MK_QKV_PF else w2_scale_base),  # [25]
            ]

            mirage_out = [
                buf_x_output.data_ptr(),           # [0]  x_output (separate intermediate, NOT residual)
                buf_k_cache[li].data_ptr(),        # [1]  k_cache
                buf_v_cache[li].data_ptr(),        # [2]  v_cache
                buf_q_workspace.data_ptr(),        # [3]  q_workspace
                buf_attn_out.data_ptr(),           # [4]  o_acc (attn output)
                buf_oproj_out.data_ptr(),          # [5]  attn_proj_out (= next layer's residual)
                buf_topk_weight.data_ptr(),        # [6]  topk_weight
                buf_routing_indices.data_ptr(),    # [7]  routing_indices
                buf_active_expert_ids.data_ptr(),  # [8]  active_expert_ids
                buf_topk_weight.data_ptr(),        # [9]  moe_routing_weight (= topk_weight)
                buf_moe_workspace_f32.data_ptr(),  # [10] moe_workspace_f32
            ]

            # Last entry: layer_output for last-layer ResAdd
            layer_output_entry = [buf_oproj_out.data_ptr()]

            assert len(mirage_in) == 26
            assert len(mirage_out) == 11
            ptr_table_host.extend(mirage_in)
            ptr_table_host.extend(mirage_out)
            ptr_table_host.extend(layer_output_entry)

    assert len(ptr_table_host) == NUM_XCDS * NUM_LAYERS * PTRS_PER_LAYER
    ptr_table_tensor = torch.tensor(ptr_table_host, dtype=torch.long, device="cuda")
    print(f"  Pointer table: {len(ptr_table_host)} entries "
          f"({NUM_XCDS}x{NUM_LAYERS}x{PTRS_PER_LAYER})")

    rank_counter_offset = NUM_LAYERS * COUNTERS_PER_LAYER
    rank_counter_slice = buf_counter[rank_counter_offset:]

    # -- Paged attention index arrays --
    qo_indptr = torch.zeros(2, dtype=torch.int32, device="cuda")
    qo_indptr[1] = 1
    kv_indptr = torch.zeros(2, dtype=torch.int32, device="cuda")
    kv_indices = torch.arange(max_num_pages, dtype=torch.int32, device="cuda")
    kv_last_page_len = torch.zeros(1, dtype=torch.int32, device="cuda")

    # -- Load fleet_mk kernel --
    fleet_mk_so = args.fleet_mk_so or os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "generated", "gpt_oss_120b.so")
    print(f"Loading fleet_mk kernel from: {fleet_mk_so}")
    fleet_mk = load_gpt_oss_120b_kernel(fleet_mk_so)
    fleet_mk.gpt_oss_120b_init()

    # -- Inference loop --
    stream = torch.cuda.current_stream()
    attn_scale = (1.0 / math.sqrt(HEAD_DIM)) * 1.44269504088896340736

    # Prefill via PyTorch
    _model_device = next(model.parameters()).device
    print(f"\n=== Prefill ({prompt_len} tokens) via PyTorch (device={_model_device}) ===")
    past_key_values = None
    with torch.no_grad():
        input_ids = tokens[:prompt_len].unsqueeze(0).to(_model_device)
        outputs = model(input_ids=input_ids, use_cache=True)
        past_key_values = outputs.past_key_values
        logits = outputs.logits

    next_token = logits[:, -1, :VOCAB_SIZE].argmax(dim=-1).item()
    tokens[prompt_len] = next_token
    print(f"Prefill complete. First token: {next_token} "
          f"('{tokenizer.decode([next_token])}')")

    # Copy PyTorch KV cache into paged KV cache buffers
    if not args.pytorch_only:
        print("Converting KV cache to paged format...")
        for li in range(NUM_LAYERS):
            k_pt = past_key_values[li][0]  # [1, num_kv_heads, seq_len, head_dim]
            v_pt = past_key_values[li][1]
            seq_len_cached = k_pt.shape[2]
            k_flat = k_pt[0].permute(1, 0, 2).reshape(seq_len_cached, -1)
            v_flat = v_pt[0].permute(1, 0, 2).reshape(seq_len_cached, -1)
            buf_k_cache[li][:seq_len_cached] = k_flat.to(torch.bfloat16)
            buf_v_cache[li][:seq_len_cached] = v_flat.to(torch.bfloat16)
        print(f"  Copied {seq_len_cached} positions into paged KV cache")

    # -- Decode --
    output_len = args.max_new_tokens if args.max_new_tokens else (
        args.max_seq_length - prompt_len - 1)
    output_len = min(output_len, args.max_seq_length - prompt_len - 1)

    print(f"\n=== Decode ({output_len} tokens) ===")

    if args.pytorch_only:
        # PyTorch path: per-token loop
        starter = torch.cuda.Event(enable_timing=True)
        ender = torch.cuda.Event(enable_timing=True)
        decode_times = []

        for di in range(output_len):
            cur_pos = prompt_len + di
            cur_token = tokens[cur_pos].item()

            if cur_token == tokenizer.eos_token_id and not args.ignore_eos:
                print(f"EOS at position {cur_pos}")
                break

            if di >= args.warmup:
                starter.record()

            input_ids_t = torch.tensor([[cur_token]], device=_model_device)
            with torch.no_grad():
                outputs = model(input_ids=input_ids_t,
                              past_key_values=past_key_values,
                              use_cache=True)
                past_key_values = outputs.past_key_values
                logits = outputs.logits
            next_token = logits[:, -1, :VOCAB_SIZE].argmax(dim=-1).item()

            if di >= args.warmup:
                ender.record()
                torch.cuda.synchronize()
                elapsed = starter.elapsed_time(ender)
                decode_times.append(elapsed)
            else:
                torch.cuda.synchronize()

            if di < 5:
                print(f"  iter {di + 1}: next_token={next_token} "
                      f"('{tokenizer.decode([next_token])}')")
            tokens[cur_pos + 1] = next_token

        end_pos = prompt_len + min(di + 1, output_len)
        generated_ids = tokens[:end_pos + 1]
        response = tokenizer.decode(generated_ids, skip_special_tokens=True)
        print(f"\n{'=' * 60}")
        print(response)
        print(f"{'=' * 60}")

        gen_tokens = len(decode_times)
        if gen_tokens > 0:
            avg_ms = sum(decode_times) / gen_tokens
            print(f"\nPrompt: {prompt_len} tokens")
            print(f"Generated: {gen_tokens} tokens (after {args.warmup} warmup)")
            print(f"Decode avg: {avg_ms:.3f} ms/token")
            print(f"Decode min: {min(decode_times):.3f} ms/token")
            print(f"Decode max: {max(decode_times):.3f} ms/token")
    else:
        # Fleet MK kernel path: per-token launch loop with hipGraph
        import struct as st

        import time as _time

        cur_token = tokens[prompt_len].item()
        cur_pos = prompt_len

        use_decode_loop = os.environ.get("FLEET_MK_DECODE_LOOP", "0") == "1"

        if use_decode_loop:
            # ============================================================
            # C-SIDE DECODE LOOP: kernel launch + argmax readback in C
            # Eliminates Python per-token overhead entirely.
            # ============================================================
            # Host-pinned buffer for output tokens (C side writes directly)
            token_output_host = torch.zeros(output_len, dtype=torch.int32).pin_memory()

            buf_decode_ctrl = torch.zeros(48, dtype=torch.uint8, device="cuda")

            # Warmup with single-step launches
            for wi in range(args.warmup):
                num_pages_used = (cur_pos + page_size) // page_size
                kv_indptr[1] = num_pages_used
                kv_last_page_len[0] = (cur_pos % page_size) + 1
                fleet_mk.gpt_oss_120b_launch(
                    1, attn_scale,
                    cos_padded.data_ptr(), sin_padded.data_ptr(),
                    qo_indptr.data_ptr(), kv_indptr.data_ptr(),
                    kv_indices.data_ptr(), kv_last_page_len.data_ptr(),
                    ptr_table_tensor.data_ptr(), buf_counter.data_ptr(),
                    final_norm_w.data_ptr(), buf_lm_norm_scratch.data_ptr(),
                    lm_head_packed.data_ptr(), lm_head_zero_bias.data_ptr(),
                    buf_argmax_out.data_ptr(),
                    None,  # logits_output (argmax-only; vLLM passes a buffer)
                    buf_timing.data_ptr(),
                    embed_weight.data_ptr(), cur_token,
                    buf_decode_ctrl.data_ptr(),
                    stream.cuda_stream,
                )
                torch.cuda.synchronize()
                next_token = buf_argmax_out[0].item()
                print(f"  warmup {wi+1}: next_token={next_token} "
                      f"('{tokenizer.decode([next_token])}')")
                tokens[cur_pos + 1] = next_token
                cur_token = next_token
                cur_pos += 1

            remaining = output_len - args.warmup

            wall_t0 = _time.perf_counter()

            # C-side decode loop: launches kernel repeatedly from C
            fleet_mk.gpt_oss_120b_decode_loop(
                1, attn_scale,
                cos_padded.data_ptr(), sin_padded.data_ptr(),
                qo_indptr.data_ptr(), kv_indptr.data_ptr(),
                kv_indices.data_ptr(), kv_last_page_len.data_ptr(),
                ptr_table_tensor.data_ptr(), buf_counter.data_ptr(),
                final_norm_w.data_ptr(), buf_lm_norm_scratch.data_ptr(),
                lm_head_packed.data_ptr(), lm_head_zero_bias.data_ptr(),
                buf_argmax_out.data_ptr(),
                None,  # logits_output (argmax-only; vLLM passes a buffer)
                buf_timing.data_ptr(),
                embed_weight.data_ptr(), cur_token,
                buf_decode_ctrl.data_ptr(),
                stream.cuda_stream,
                # Decode loop params
                remaining,
                cur_pos,
                page_size,
                ctypes.cast(token_output_host.data_ptr(), ctypes.c_void_p),
            )

            wall_t1 = _time.perf_counter()
            wall_elapsed = (wall_t1 - wall_t0) * 1000

            # Read generated tokens from host-pinned buffer
            gen_tokens = token_output_host[:remaining].tolist()
            actual_gen = len(gen_tokens)
            print(f"\n  C-side decode loop generated {actual_gen} tokens")
            for gi, gtok in enumerate(gen_tokens[:5]):
                print(f"  token {gi}: {gtok} ('{tokenizer.decode([gtok])}')")

            # Reconstruct token sequence
            for gi, gtok in enumerate(gen_tokens):
                tokens[cur_pos + 1 + gi] = gtok
            end_pos = cur_pos + actual_gen
            generated_ids = tokens[:end_pos + 1]
            response = tokenizer.decode(generated_ids, skip_special_tokens=True)
            print(f"\n{'=' * 60}")
            print(response)
            print(f"{'=' * 60}")

            wall_avg = wall_elapsed / actual_gen if actual_gen > 0 else 0
            print(f"\nPrompt: {prompt_len} tokens")
            print(f"Generated: {actual_gen} tokens (C-side loop, {args.warmup} warmup)")
            print(f"Wall total: {wall_elapsed:.3f} ms")
            print(f"Wall avg: {wall_avg:.3f} ms/token")

        elif os.environ.get("FLEET_MK_PIPE", "0") == "1":
            # ============================================================
            # PIPELINED GRAPH: queue ALL decode steps, no host sync between
            # Bridge kernel handles argmax→token + KV metadata between steps
            # ============================================================
            buf_decode_ctrl = torch.zeros(48, dtype=torch.uint8, device="cuda")

            # GPU-side token pointer and step counter
            buf_cur_token = torch.zeros(1, dtype=torch.int32, device="cuda")
            buf_step_counter = torch.zeros(1, dtype=torch.int32, device="cuda")
            token_output_buf = torch.zeros(output_len, dtype=torch.int32, device="cuda")

            moe_barrier_bytes = buf_moe_barrier.nelement() * buf_moe_barrier.element_size()
            workspace_bytes = buf_moe_workspace_f32.nelement() * buf_moe_workspace_f32.element_size()

            # Warmup with regular launches to establish correct state
            for wi in range(args.warmup):
                num_pages_used = (cur_pos + page_size) // page_size
                kv_indptr[1] = num_pages_used
                kv_last_page_len[0] = (cur_pos % page_size) + 1
                fleet_mk.gpt_oss_120b_launch(
                    1, attn_scale,
                    cos_padded.data_ptr(), sin_padded.data_ptr(),
                    qo_indptr.data_ptr(), kv_indptr.data_ptr(),
                    kv_indices.data_ptr(), kv_last_page_len.data_ptr(),
                    ptr_table_tensor.data_ptr(), buf_counter.data_ptr(),
                    final_norm_w.data_ptr(), buf_lm_norm_scratch.data_ptr(),
                    lm_head_packed.data_ptr(), lm_head_zero_bias.data_ptr(),
                    buf_argmax_out.data_ptr(),
                    None,  # logits_output (argmax-only; vLLM passes a buffer)
                    buf_timing.data_ptr(),
                    embed_weight.data_ptr(), cur_token,
                    buf_decode_ctrl.data_ptr(),
                    stream.cuda_stream,
                )
                torch.cuda.synchronize()
                next_token = buf_argmax_out[0].item()
                print(f"  warmup {wi+1}: next_token={next_token} "
                      f"('{tokenizer.decode([next_token])}')")
                tokens[cur_pos + 1] = next_token
                cur_token = next_token
                cur_pos += 1

            remaining = output_len - args.warmup

            # Set initial state for pipe: write cur_token to GPU buffer
            buf_cur_token[0] = cur_token
            # Update KV metadata for first pipe step
            num_pages_used = (cur_pos + page_size) // page_size
            kv_indptr[1] = num_pages_used
            kv_last_page_len[0] = (cur_pos % page_size) + 1
            torch.cuda.synchronize()

            # Capture pipelined graph
            fleet_mk.gpt_oss_120b_pipe_capture(
                1, attn_scale,
                cos_padded.data_ptr(), sin_padded.data_ptr(),
                qo_indptr.data_ptr(), kv_indptr.data_ptr(),
                kv_indices.data_ptr(), kv_last_page_len.data_ptr(),
                ptr_table_tensor.data_ptr(), buf_counter.data_ptr(),
                final_norm_w.data_ptr(), buf_lm_norm_scratch.data_ptr(),
                lm_head_packed.data_ptr(), lm_head_zero_bias.data_ptr(),
                buf_argmax_out.data_ptr(),
                None,  # logits_output (argmax-only; vLLM passes a buffer)
                buf_timing.data_ptr(),
                embed_weight.data_ptr(), cur_token,
                buf_decode_ctrl.data_ptr(),
                stream.cuda_stream,
                # Bridge kernel args
                buf_moe_barrier.data_ptr(),
                buf_moe_barrier.nelement(),
                buf_cur_token.data_ptr(),
                token_output_buf.data_ptr(),
                buf_step_counter.data_ptr(),
                cur_pos,
                page_size,
                # Workspace
                buf_moe_workspace_f32.data_ptr(),
                workspace_bytes,
            )

            starter = torch.cuda.Event(enable_timing=True)
            ender = torch.cuda.Event(enable_timing=True)

            # Queue ALL decode steps at once — no host sync between!
            starter.record()
            fleet_mk.gpt_oss_120b_pipe_launch_all(
                stream.cuda_stream,
                remaining,
            )
            ender.record()
            torch.cuda.synchronize()

            gpu_elapsed = starter.elapsed_time(ender)
            gpu_avg = gpu_elapsed / remaining if remaining > 0 else 0

            # Read generated tokens from GPU buffer
            gen_tokens = token_output_buf[:remaining].cpu().tolist()
            for gi, gtok in enumerate(gen_tokens[:5]):
                print(f"  token {gi}: {gtok} ('{tokenizer.decode([gtok])}')")

            # Reconstruct token sequence
            for gi, gtok in enumerate(gen_tokens):
                tokens[cur_pos + 1 + gi] = gtok
            end_pos = cur_pos + remaining
            generated_ids = tokens[:end_pos + 1]
            response = tokenizer.decode(generated_ids, skip_special_tokens=True)
            print(f"\n{'=' * 60}")
            print(response)
            print(f"{'=' * 60}")

            print(f"\nPrompt: {prompt_len} tokens")
            print(f"Generated: {remaining} tokens (pipelined graph, {args.warmup} warmup)")
            print(f"GPU total: {gpu_elapsed:.3f} ms")
            print(f"GPU avg: {gpu_avg:.3f} ms/token (zero host overhead)")

            fleet_mk.gpt_oss_120b_pipe_destroy()

        else:
            # ============================================================
            # PER-TOKEN LAUNCH LOOP (legacy path)
            # ============================================================
            # Build a dummy DecodeControl (not used by kernel but still passed)
            buf_decode_ctrl = torch.zeros(48, dtype=torch.uint8, device="cuda")

            # We need a GPU-side token ID buffer so we can update it between graph launches
            buf_cur_token = torch.zeros(1, dtype=torch.int32, device="cuda")

            starter = torch.cuda.Event(enable_timing=True)
            ender = torch.cuda.Event(enable_timing=True)
            decode_times = []
            wall_times = []

            # Helper to launch one decode step
            def launch_one_step(cur_tok_id):
                fleet_mk.gpt_oss_120b_launch(
                    1, attn_scale,
                    cos_padded.data_ptr(), sin_padded.data_ptr(),
                    qo_indptr.data_ptr(), kv_indptr.data_ptr(),
                    kv_indices.data_ptr(), kv_last_page_len.data_ptr(),
                    ptr_table_tensor.data_ptr(), buf_counter.data_ptr(),
                    final_norm_w.data_ptr(), buf_lm_norm_scratch.data_ptr(),
                    lm_head_packed.data_ptr(), lm_head_zero_bias.data_ptr(),
                    buf_argmax_out.data_ptr(),
                    None,  # logits_output (argmax-only; vLLM passes a buffer)
                    buf_timing.data_ptr(),
                    embed_weight.data_ptr(), cur_tok_id,
                    buf_decode_ctrl.data_ptr(),
                    stream.cuda_stream,
                )

            use_graph = os.environ.get("FLEET_MK_GRAPH", "0") == "1"
            graph_captured = False

            # Buffer sizes for graph capture
            moe_barrier_bytes = buf_moe_barrier.nelement() * buf_moe_barrier.element_size()
            workspace_bytes = buf_moe_workspace_f32.nelement() * buf_moe_workspace_f32.element_size()

            for di in range(output_len):
                if cur_token == tokenizer.eos_token_id and not args.ignore_eos:
                    print(f"EOS at position {cur_pos}")
                    break

                wall_t0 = _time.perf_counter()

                # Update KV metadata
                num_pages_used = (cur_pos + page_size) // page_size
                kv_indptr[1] = num_pages_used
                kv_last_page_len[0] = (cur_pos % page_size) + 1

                if use_graph and graph_captured:
                    # Graph replay: zero + kernel in one submission
                    if di >= args.warmup:
                        starter.record()
                    fleet_mk.gpt_oss_120b_graph_launch(
                        cur_token,
                        stream.cuda_stream,
                    )
                elif use_graph and di == args.warmup - 1:
                    # Last warmup: capture graph
                    fleet_mk.gpt_oss_120b_graph_capture(
                        1, attn_scale,
                        cos_padded.data_ptr(), sin_padded.data_ptr(),
                        qo_indptr.data_ptr(), kv_indptr.data_ptr(),
                        kv_indices.data_ptr(), kv_last_page_len.data_ptr(),
                        ptr_table_tensor.data_ptr(), buf_counter.data_ptr(),
                        final_norm_w.data_ptr(), buf_lm_norm_scratch.data_ptr(),
                        lm_head_packed.data_ptr(), lm_head_zero_bias.data_ptr(),
                        buf_argmax_out.data_ptr(),
                        None,  # logits_output (argmax-only; vLLM passes a buffer)
                        buf_timing.data_ptr(),
                        embed_weight.data_ptr(), cur_token,
                        buf_decode_ctrl.data_ptr(),
                        stream.cuda_stream,
                        buf_moe_barrier.data_ptr(), moe_barrier_bytes,
                        buf_moe_workspace_f32.data_ptr(), workspace_bytes,
                        0, 0,  # counter buf: monotonic, no zeroing needed
                    )
                    graph_captured = True
                    print(f"  [hipGraph captured at warmup iter {di + 1}]")
                    # Now replay the captured graph for this iteration
                    fleet_mk.gpt_oss_120b_graph_launch(
                        cur_token,
                        stream.cuda_stream,
                    )
                else:
                    # Regular launch (warmup or non-graph mode)
                    # MoE barrier: zeroed by kernel at end of each step (first iter uses pre-zeroed buf)
                    # Counter buf: monotonic counters, no zeroing needed
                    # buf_moe_workspace_f32: zeroed by kernel's ResAdd (last layer)
                    if di >= args.warmup:
                        starter.record()
                    launch_one_step(cur_token)

                if di >= args.warmup:
                    ender.record()
                    torch.cuda.synchronize()
                    elapsed = starter.elapsed_time(ender)
                    decode_times.append(elapsed)
                    wall_t1 = _time.perf_counter()
                    wall_times.append((wall_t1 - wall_t0) * 1000)
                else:
                    torch.cuda.synchronize()

                next_token = buf_argmax_out[0].item()
                if di < 5:
                    print(f"  iter {di + 1}: next_token={next_token} "
                          f"('{tokenizer.decode([next_token])}')")

                tokens[cur_pos + 1] = next_token
                cur_token = next_token
                cur_pos += 1

            end_pos = cur_pos
            generated_ids = tokens[:end_pos + 1]
            response = tokenizer.decode(generated_ids, skip_special_tokens=True)
            print(f"\n{'=' * 60}")
            print(response)
            print(f"{'=' * 60}")

            gen_tokens = len(decode_times)
            if gen_tokens > 0:
                avg_ms = sum(decode_times) / gen_tokens
                # Count outliers (>5ms)
                outliers = [t for t in decode_times if t > 5.0]
                non_outlier = [t for t in decode_times if t <= 5.0]
                print(f"\nPrompt: {prompt_len} tokens")
                print(f"Generated: {gen_tokens} tokens (after {args.warmup} warmup)")
                print(f"Decode avg: {avg_ms:.3f} ms/token")
                print(f"Decode min: {min(decode_times):.3f} ms/token")
                print(f"Decode max: {max(decode_times):.3f} ms/token")
                if outliers:
                    print(f"Outliers (>5ms): {len(outliers)} tokens, "
                          f"avg={sum(outliers)/len(outliers):.1f}ms")
                if non_outlier:
                    print(f"Non-outlier avg: {sum(non_outlier)/len(non_outlier):.3f} ms/token")
                if wall_times:
                    wall_non_outlier = [w for w in wall_times if w <= 5.0]
                    if wall_non_outlier:
                        print(f"Wall avg (non-outlier): {sum(wall_non_outlier)/len(wall_non_outlier):.3f} ms/token")
                        gpu_non_outlier = [t for t, w in zip(decode_times, wall_times) if w <= 5.0]
                        if gpu_non_outlier:
                            overhead = sum(wall_non_outlier)/len(wall_non_outlier) - sum(gpu_non_outlier)/len(gpu_non_outlier)
                            print(f"Python overhead: {overhead*1000:.0f} us/token")

    # -- Subphase timing readback --
    if os.environ.get("FLEET_MK_SUBPHASE_TIMING"):
        timing_data = buf_timing.cpu().numpy()
        # GPU clock is 100MHz on MI350 (10ns ticks)
        GPU_CLOCK_NS = 10.0
        print(f"\n{'=' * 60}")
        print("SUBPHASE TIMING (last decode step, XCD0/worker0)")
        print(f"{'=' * 60}")
        phase_names = [
            "layer_start", "after_rmsnorm1", "after_qkv_barrier",
            "after_rope", "after_attn_compute", "after_attn_barrier",
            "after_oproj_gemm", "after_ffn_mid_barrier", "after_router_gemm",
            "after_topk", "after_w13", "after_w13_barrier",
            "after_w2", "after_w2_barrier"
        ]
        # Print per-layer breakdown for layers 0, 1, last
        for li in [0, 1, NUM_LAYERS - 1]:
            base = li * TIMING_SLOTS_PER_LAYER
            timestamps = timing_data[base:base + TIMING_SLOTS_PER_LAYER]
            if timestamps[0] == 0:
                print(f"  Layer {li}: no timing data")
                continue
            print(f"\n  Layer {li}:")
            for pi in range(1, TIMING_SLOTS_PER_LAYER):
                if timestamps[pi] == 0:
                    break
                delta_ns = (timestamps[pi] - timestamps[pi-1]) * GPU_CLOCK_NS
                delta_us = delta_ns / 1000.0
                print(f"    {phase_names[pi-1]:30s} -> {phase_names[pi]:30s}: {delta_us:8.1f} us")
            total_ns = (timestamps[TIMING_SLOTS_PER_LAYER-1] - timestamps[0]) * GPU_CLOCK_NS
            print(f"    {'TOTAL':62s}: {total_ns/1000.0:8.1f} us")

        # Print average across all layers
        print(f"\n  Average across {NUM_LAYERS} layers:")
        avg_deltas = [0.0] * (TIMING_SLOTS_PER_LAYER - 1)
        valid_layers = 0
        for li in range(NUM_LAYERS):
            base = li * TIMING_SLOTS_PER_LAYER
            timestamps = timing_data[base:base + TIMING_SLOTS_PER_LAYER]
            if timestamps[0] == 0 or timestamps[-1] == 0:
                continue
            valid_layers += 1
            for pi in range(1, TIMING_SLOTS_PER_LAYER):
                avg_deltas[pi-1] += (timestamps[pi] - timestamps[pi-1]) * GPU_CLOCK_NS / 1000.0
        if valid_layers > 0:
            total_avg = 0.0
            for pi in range(TIMING_SLOTS_PER_LAYER - 1):
                avg_deltas[pi] /= valid_layers
                total_avg += avg_deltas[pi]
                print(f"    {phase_names[pi]:30s} -> {phase_names[pi+1]:30s}: {avg_deltas[pi]:8.1f} us")
            print(f"    {'TOTAL':62s}: {total_avg:8.1f} us")
            print(f"    {'TOTAL x 36 layers':62s}: {total_avg * 36 / 1000.0:8.3f} ms")

    fleet_mk.gpt_oss_120b_finalize()
    print("\nDone.")


if __name__ == "__main__":
    main()
